'use client';
import {useEffect} from 'react';
export function V8DesignLayoutEnhancer(){useEffect(()=>{const apply=()=>{const main=document.querySelector('.v7-workspace main');const article=main?.querySelector('article');if(!main||!article)return;main.classList.add('v8-app-flow');article.classList.add('v8-song-studio');const input=main.querySelector('input[placeholder*="Suno"]');input?.parentElement?.classList.add('v8-link-card');const songHead=article.firstElementChild;songHead?.classList.add('v8-song-detail');const controls=article.querySelector('.mt-6.grid');controls?.classList.add('v8-studio-controls');const result=article.querySelector('video');result?.parentElement?.classList.add('v8-result-card')};apply();const o=new MutationObserver(apply);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);return <style>{`
.v8-app-flow{max-width:none!important}.v8-link-card{padding:16px;border:1px solid rgba(139,92,246,.18);border-radius:18px;background:linear-gradient(145deg,rgba(124,58,237,.09),rgba(8,20,33,.96));box-shadow:0 14px 50px rgba(0,0,0,.16)}
.v8-song-studio{overflow:hidden}.v8-song-detail{padding-bottom:18px;border-bottom:1px solid rgba(255,255,255,.07)}.v8-song-detail img{box-shadow:0 12px 35px rgba(0,0,0,.28)}
.v8-studio-controls{position:relative}.v8-studio-controls:before{content:'Tạo video visualizer';display:block;margin-bottom:2px;font-size:16px;font-weight:800}.v8-studio-controls:after{content:'Preset · Tùy chỉnh · Lyrics · Hiệu ứng';display:block;order:-1;margin-bottom:8px;font-size:10px;letter-spacing:.04em;color:rgba(255,255,255,.35)}
.v8-result-card{border-radius:16px!important;overflow:hidden}.v8-app-flow button{transition:transform .16s ease,background .16s ease,border-color .16s ease}.v8-app-flow button:active{transform:scale(.98)}
@media(min-width:900px){.v8-song-studio{display:grid!important;grid-template-columns:minmax(0,1.45fr) minmax(320px,.75fr);column-gap:22px}.v8-song-detail{grid-column:1/-1}.v8-studio-controls{grid-column:1}.v8-song-studio>.mt-5,.v8-song-studio>.mt-4{grid-column:2}.v8-link-card{max-width:760px}}
@media(max-width:767px){.v8-link-card{margin-top:12px!important;padding:12px}.v8-link-card input{height:52px!important}.v8-song-studio{border-radius:18px!important}.v8-song-detail{display:grid!important;grid-template-columns:82px minmax(0,1fr);gap:12px!important}.v8-song-detail img{width:82px!important;height:82px!important;border-radius:14px!important}.v8-song-detail audio{grid-column:1/-1;width:100%;height:38px}.v8-studio-controls{gap:12px!important}.v8-studio-controls>div{padding:12px;border:1px solid rgba(255,255,255,.055);border-radius:14px;background:rgba(255,255,255,.018)}.v8-studio-controls button{min-height:34px}.v8-app-flow video{border-radius:14px!important}.v8-app-flow article>.mt-4.grid{position:sticky;bottom:68px;z-index:20;padding:8px;margin-left:-6px;margin-right:-6px;border:1px solid rgba(255,255,255,.07);border-radius:16px;background:rgba(6,16,29,.9);backdrop-filter:blur(16px)}}
`}</style>}
