'use client';
import {useEffect,useState} from 'react';
import {Clock3,ExternalLink,Play,Trash2} from 'lucide-react';

type HistoryItem={id:string;url:string;title:string;creator?:string;cover?:string;kind:'link'|'video';createdAt:number;videoUrl?:string};
const KEY='suno-tools-v8-history';
function read():HistoryItem[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function write(items:HistoryItem[]){localStorage.setItem(KEY,JSON.stringify(items.slice(0,50)));window.dispatchEvent(new Event('suno-history-change'))}
function add(item:HistoryItem){const old=read().filter(x=>x.id!==item.id);write([item,...old])}
function ago(ts:number){const d=Date.now()-ts;if(d<60000)return'Vừa xong';if(d<3600000)return`${Math.floor(d/60000)} phút trước`;if(d<86400000)return`${Math.floor(d/3600000)} giờ trước`;return new Date(ts).toLocaleDateString('vi-VN')}
export function V8HistoryEnhancer(){const[items,setItems]=useState<HistoryItem[]>([]);useEffect(()=>{const refresh=()=>setItems(read());refresh();window.addEventListener('suno-history-change',refresh);const onInput=(e:Event)=>{const el=e.target as HTMLInputElement;if(el?.tagName==='INPUT'&&/^https:\/\/(?:[^/]+\.)?suno\.com\//i.test(el.value.trim())){const url=el.value.trim();add({id:`link:${url}`,url,title:'Link Suno',kind:'link',createdAt:Date.now()})}};document.addEventListener('change',onInput,true);const obs=new MutationObserver(()=>{document.querySelectorAll('video[src]').forEach(v=>{const video=v as HTMLVideoElement;const src=video.src;if(!src||video.dataset.historySaved)return;video.dataset.historySaved='1';const article=video.closest('article');const title=article?.querySelector('h2')?.textContent?.trim()||'Video visualizer';add({id:`video:${Date.now()}:${src.slice(-24)}`,url:location.href,title,kind:'video',createdAt:Date.now(),videoUrl:src})})});obs.observe(document.body,{childList:true,subtree:true});return()=>{obs.disconnect();document.removeEventListener('change',onInput,true);window.removeEventListener('suno-history-change',refresh)}},[]);
 const remove=(id:string)=>write(read().filter(x=>x.id!==id));const clear=()=>write([]);
 return <section id="library-history" className="mt-5 rounded-2xl border border-white/[.07] bg-[#081421] p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-violet-300">Thư viện</p><h2 className="mt-1 text-base font-bold">Lịch sử link & video đã làm</h2><p className="mt-1 text-xs text-white/35">Lưu trên thiết bị này, tối đa 50 mục gần nhất.</p></div>{items.length>0&&<button onClick={clear} className="rounded-lg bg-white/[.05] px-3 py-2 text-[11px] text-white/45">Xóa tất cả</button>}</div>{items.length===0?<div className="mt-4 rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-white/30"><Clock3 className="mx-auto mb-2 size-5"/>Chưa có lịch sử. Link Suno và video render xong sẽ xuất hiện ở đây.</div>:<div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map(x=><div key={x.id} className="flex min-w-0 items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.025] p-3">{x.cover?<img src={x.cover} alt="" className="size-12 rounded-lg object-cover"/>:<div className="grid size-12 shrink-0 place-items-center rounded-lg bg-violet-500/10">{x.kind==='video'?<Play className="size-4 text-violet-300"/>:<ExternalLink className="size-4 text-cyan-300"/>}</div>}<div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{x.title}</p><p className="mt-1 truncate text-[10px] text-white/30">{x.kind==='video'?'Video đã render':'Link Suno'} · {ago(x.createdAt)}</p><div className="mt-2 flex gap-2">{x.kind==='link'?<button onClick={()=>{const input=document.querySelector('input[placeholder*="Suno"]') as HTMLInputElement|null;if(input){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(input,x.url);input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollIntoView({behavior:'smooth',block:'center'})}} className="text-[10px] font-bold text-cyan-300">Mở lại</button>:x.videoUrl&&<a href={x.videoUrl} target="_blank" rel="noreferrer" className="text-[10px] font-bold text-violet-300">Xem video</a>}</div></div><button onClick={()=>remove(x.id)} aria-label="Xóa" className="rounded-lg p-2 text-white/25 hover:bg-white/5 hover:text-white/60"><Trash2 className="size-3.5"/></button></div>)}</div>}</section>}
