'use client';
export type VideoEffect='snow'|'smoke'|'leaves'|'petals'|'rain'|'bokeh'|'embers'|'sparkles'|'feathers'|'film'|'dust'|'fireflies'|'stars'|'lightleak'|'fog'|'confetti'|'hearts'|'butterflies'|'snowstorm'|'vignette';
export type EffectConfig={effects:VideoEffect[];intensity:number;speed:number;opacity:number;wind:number};
export const VIDEO_EFFECTS:{id:VideoEffect;label:string;icon:string;group:'nature'|'light'|'mood'|'party'}[]=[
{id:'snow',label:'Tuyết',icon:'❄️',group:'nature'},{id:'snowstorm',label:'Bão tuyết',icon:'🌨️',group:'nature'},{id:'smoke',label:'Khói',icon:'🌫️',group:'mood'},{id:'fog',label:'Sương mù',icon:'☁️',group:'mood'},{id:'leaves',label:'Lá rơi',icon:'🍂',group:'nature'},{id:'petals',label:'Cánh hoa',icon:'🌸',group:'nature'},{id:'rain',label:'Mưa',icon:'🌧️',group:'nature'},{id:'dust',label:'Bụi sáng',icon:'🫧',group:'light'},{id:'bokeh',label:'Bokeh',icon:'💫',group:'light'},{id:'fireflies',label:'Đom đóm',icon:'🟡',group:'light'},{id:'stars',label:'Sao trời',icon:'🌟',group:'light'},{id:'lightleak',label:'Light leak',icon:'🌈',group:'light'},{id:'embers',label:'Tàn lửa',icon:'🔥',group:'mood'},{id:'sparkles',label:'Lấp lánh',icon:'✨',group:'light'},{id:'feathers',label:'Lông vũ',icon:'🪶',group:'nature'},{id:'butterflies',label:'Bướm bay',icon:'🦋',group:'nature'},{id:'hearts',label:'Trái tim',icon:'💜',group:'party'},{id:'confetti',label:'Confetti',icon:'🎊',group:'party'},{id:'film',label:'Film grain',icon:'🎞️',group:'mood'},{id:'vignette',label:'Vignette',icon:'◉',group:'mood'}];
function hash(n:number){const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)}function count(base:number,c:EffectConfig){return Math.max(3,Math.round(base*Math.max(.2,c.intensity)))}
export function drawVideoEffects(ctx:CanvasRenderingContext2D,w:number,h:number,t:number,c?:EffectConfig){if(!c?.effects?.length)return;const op=Math.max(.05,Math.min(1,c.opacity)),speed=Math.max(.2,Math.min(3,c.speed)),wind=Math.max(-2,Math.min(2,c.wind));ctx.save();for(const effect of c.effects){
if(['snow','snowstorm','petals','leaves','feathers','butterflies','confetti','hearts'].includes(effect)){const n=count(effect==='snowstorm'?150:effect==='snow'?70:effect==='confetti'?55:32,c);for(let i=0;i<n;i++){const r=hash(i+11),r2=hash(i+41),fall=(t*speed*(18+50*r)+r2*h*1.3)%(h+80)-40,x=((r*w+t*wind*(12+24*r2)+Math.sin(t*.7+i)*18)%(w+80)+w+80)%(w+80)-40;ctx.globalAlpha=op*(.35+.65*r2);ctx.save();ctx.translate(x,fall);ctx.rotate(t*(.25+r)+i);if(effect==='snow'||effect==='snowstorm'){ctx.fillStyle='white';ctx.beginPath();ctx.arc(0,0,1.5+4*r,0,Math.PI*2);ctx.fill()}else if(effect==='petals'){ctx.fillStyle='rgba(255,185,215,.9)';ctx.beginPath();ctx.ellipse(0,0,3+5*r,1.5+3*r2,.5,0,Math.PI*2);ctx.fill()}else if(effect==='leaves'){ctx.fillStyle=`rgba(${150+Math.round(70*r)},${65+Math.round(75*r2)},28,.9)`;ctx.beginPath();ctx.ellipse(0,0,4+7*r,2+4*r2,.5,0,Math.PI*2);ctx.fill()}else if(effect==='feathers'){ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=1.2+2*r;ctx.beginPath();ctx.moveTo(-6,0);ctx.quadraticCurveTo(0,5,8,0);ctx.stroke()}else if(effect==='butterflies'){ctx.fillStyle=i%2?'#c4b5fd':'#f9a8d4';ctx.beginPath();ctx.ellipse(-4,0,5,3,.5,0,Math.PI*2);ctx.ellipse(4,0,5,3,-.5,0,Math.PI*2);ctx.fill()}else if(effect==='hearts'){ctx.fillStyle='rgba(244,114,182,.85)';ctx.font=`${12+18*r}px sans-serif`;ctx.fillText('♥',0,0)}else{ctx.fillStyle=`hsl(${Math.floor(r*360)} 85% 65%)`;ctx.fillRect(-2,-5,4+5*r,8+8*r2)}ctx.restore()}}
else if(effect==='rain'){ctx.strokeStyle='rgba(190,220,255,.72)';ctx.lineWidth=Math.max(1,w*.001);for(let i=0;i<count(85,c);i++){const r=hash(i+90),y=(hash(i+120)*h+t*speed*(240+180*r))%(h+50)-25,x=(r*w+t*wind*35)%w;ctx.globalAlpha=op*(.25+.55*hash(i+7));ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+wind*8,y+12+20*r);ctx.stroke()}}
else if(['bokeh','dust','fireflies','stars','sparkles','embers'].includes(effect)){const n=count(effect==='dust'?80:effect==='stars'?55:42,c);for(let i=0;i<n;i++){const r=hash(i+280),rise=effect==='embers'||effect==='fireflies',y=rise?h-((hash(i+310)*h+t*speed*(18+45*r))%(h+30)):(hash(i+310)*h+Math.sin(t*.4+i)*18+h)%h,x=((r*w+t*wind*12+Math.sin(t+i)*10)%w+w)%w,rad=effect==='bokeh'?8+28*hash(i+370):.8+3*hash(i+370);ctx.globalAlpha=op*(effect==='bokeh'?.12:.25+.65*hash(i+340));ctx.fillStyle=effect==='embers'?'#fb923c':effect==='fireflies'?'#fde68a':effect==='dust'?'#e2e8f0':effect==='stars'?'#fff':'#fff7c2';ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill()}}
else if(effect==='smoke'||effect==='fog'){const n=count(effect==='fog'?12:7,c);for(let i=0;i<n;i++){const r=hash(i+410),x=w*(.08+.84*r)+Math.sin(t*.18*speed+i)*w*.08+wind*t*4,y=h*(.2+.65*hash(i+440))-t*speed*(effect==='fog'?2:5),rad=w*(effect==='fog'?.13+.14*hash(i+470):.07+.12*hash(i+470)),g=ctx.createRadialGradient(x,y,0,x,y,rad);g.addColorStop(0,`rgba(220,225,235,${op*(effect==='fog'?.13:.09)})`);g.addColorStop(1,'rgba(220,225,235,0)');ctx.globalAlpha=1;ctx.fillStyle=g;ctx.fillRect(x-rad,y-rad,rad*2,rad*2)}}
else if(effect==='lightleak'){const x=w*(.15+.7*((Math.sin(t*.18*speed)+1)/2)),g=ctx.createRadialGradient(x,h*.35,0,x,h*.35,w*.65);g.addColorStop(0,`rgba(251,113,133,${op*.22})`);g.addColorStop(.45,`rgba(168,85,247,${op*.1})`);g.addColorStop(1,'rgba(0,0,0,0)');ctx.globalAlpha=1;ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
else if(effect==='film'){ctx.globalAlpha=op*.12;ctx.fillStyle='white';for(let i=0;i<count(90,c);i++){const x=hash(i+Math.floor(t*12)*101)*w,y=hash(i+Math.floor(t*12)*137)*h,s=.5+1.5*hash(i+520);ctx.fillRect(x,y,s,s)}}
else if(effect==='vignette'){const g=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.25,w/2,h/2,Math.max(w,h)*.7);g.addColorStop(.45,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${op*.7})`);ctx.globalAlpha=1;ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}}ctx.restore()}
