'use client';

export type ProcessedFormat = 'mp3' | 'wav' | 'm4a';
export type TikTokCalibrationResult={beforeLufs:number;beforePeak:number;afterLufs:number;afterPeak:number;gainDb:number};
function db(v:number){return 20*Math.log10(Math.max(v,1e-12))}
function measure(buffer:AudioBuffer){let sum=0,peak=0,count=0;for(let ch=0;ch<buffer.numberOfChannels;ch++){const d=buffer.getChannelData(ch);for(let i=0;i<d.length;i+=4){const v=d[i];sum+=v*v;peak=Math.max(peak,Math.abs(v));count++}}const rms=Math.sqrt(sum/Math.max(1,count));return{lufs:-.691+db(rms),peak:db(peak),linearPeak:peak}}
function wavBlob(buffer:AudioBuffer){const channels=Math.min(2,buffer.numberOfChannels),bytes=44+buffer.length*channels*2,out=new ArrayBuffer(bytes),v=new DataView(out);let p=0;const s=(x:string)=>{for(const c of x)v.setUint8(p++,c.charCodeAt(0))};s('RIFF');v.setUint32(p,bytes-8,true);p+=4;s('WAVEfmt ');v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,channels,true);p+=2;v.setUint32(p,buffer.sampleRate,true);p+=4;v.setUint32(p,buffer.sampleRate*channels*2,true);p+=4;v.setUint16(p,channels*2,true);p+=2;v.setUint16(p,16,true);p+=2;s('data');v.setUint32(p,buffer.length*channels*2,true);p+=4;for(let i=0;i<buffer.length;i++)for(let ch=0;ch<channels;ch++){const x=Math.max(-1,Math.min(1,buffer.getChannelData(ch)[i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([out],{type:'audio/wav'})}
async function decode(source:Blob){const bytes=await source.arrayBuffer(),AudioCtx=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtx)throw new Error('Trình duyệt không hỗ trợ xử lý audio.');const ctx=new AudioCtx();try{return await ctx.decodeAudioData(bytes.slice(0))}finally{await ctx.close()}}
async function socialChain(decoded:AudioBuffer){const sampleRate=48000,frames=Math.ceil(decoded.duration*sampleRate),offline=new OfflineAudioContext(2,frames,sampleRate),src=offline.createBufferSource();src.buffer=decoded;const hp=offline.createBiquadFilter();hp.type='highpass';hp.frequency.value=30;hp.Q.value=.707;const sub=offline.createBiquadFilter();sub.type='lowshelf';sub.frequency.value=80;sub.gain.value=-.8;const lowMid=offline.createBiquadFilter();lowMid.type='peaking';lowMid.frequency.value=220;lowMid.Q.value=1;lowMid.gain.value=.7;const presence=offline.createBiquadFilter();presence.type='peaking';presence.frequency.value=3000;presence.Q.value=1.2;presence.gain.value=1.2;const high=offline.createBiquadFilter();high.type='highshelf';high.frequency.value=8000;high.gain.value=-.7;const comp=offline.createDynamicsCompressor();comp.threshold.value=-18;comp.knee.value=10;comp.ratio.value=1.7;comp.attack.value=.02;comp.release.value=.11;src.connect(hp).connect(sub).connect(lowMid).connect(presence).connect(high).connect(comp).connect(offline.destination);src.start();return offline.startRendering()}
export async function renderTikTokCalibratedAudio(source:Blob){const decoded=await decode(source),before=measure(decoded),rendered=await socialChain(decoded),pre=measure(rendered),target=-14,ceiling=Math.pow(10,-1/20),loudnessGain=Math.pow(10,(target-pre.lufs)/20),peakGain=pre.linearPeak>0?ceiling/pre.linearPeak:1,gain=Math.max(.25,Math.min(4,loudnessGain,peakGain)),gainDb=db(gain),normalized=new AudioBuffer({length:rendered.length,numberOfChannels:2,sampleRate:rendered.sampleRate});for(let ch=0;ch<2;ch++){const input=rendered.getChannelData(Math.min(ch,rendered.numberOfChannels-1)),out=normalized.getChannelData(ch);for(let i=0;i<input.length;i++)out[i]=Math.max(-ceiling,Math.min(ceiling,input[i]*gain))}const after=measure(normalized);return{blob:wavBlob(normalized),metrics:{beforeLufs:before.lufs,beforePeak:before.peak,afterLufs:after.lufs,afterPeak:after.peak,gainDb} satisfies TikTokCalibrationResult}}
export async function renderTikTokLikeAudio(source: Blob) {return (await renderTikTokCalibratedAudio(source)).blob}

export async function renderLoopedFadeAudio(source:Blob,trimStart:number,trimEnd:number,outputStart:number,segmentDuration:number,totalDuration:number,fadeIn:number,fadeOut:number){
 const decoded=await decode(source),sampleRate=Math.min(48000,decoded.sampleRate||48000),frames=Math.max(1,Math.ceil(segmentDuration*sampleRate)),offline=new OfflineAudioContext(Math.min(2,Math.max(1,decoded.numberOfChannels)),frames,sampleRate),src=offline.createBufferSource(),gain=offline.createGain(),loopDuration=Math.max(.05,trimEnd-trimStart),offset=trimStart+(((outputStart%loopDuration)+loopDuration)%loopDuration);src.buffer=decoded;src.loop=true;src.loopStart=trimStart;src.loopEnd=trimEnd;src.connect(gain).connect(offline.destination);
 const globalEnd=outputStart+segmentDuration,fi=Math.max(0,Math.min(fadeIn,totalDuration)),fo=Math.max(0,Math.min(fadeOut,totalDuration)),gainAt=(t:number)=>Math.max(0,Math.min(1,fi>0?t/fi:1,fo>0?(totalDuration-t)/fo:1));gain.gain.setValueAtTime(gainAt(outputStart),0);const inBoundary=fi-outputStart;if(inBoundary>0&&inBoundary<segmentDuration)gain.gain.linearRampToValueAtTime(1,inBoundary);const outBoundary=totalDuration-fo-outputStart;if(fo>0&&outBoundary>0&&outBoundary<segmentDuration){gain.gain.setValueAtTime(1,outBoundary);gain.gain.linearRampToValueAtTime(gainAt(globalEnd),segmentDuration)}else gain.gain.linearRampToValueAtTime(gainAt(globalEnd),segmentDuration);src.start(0,offset);src.stop(segmentDuration);return wavBlob(await offline.startRendering())
}

export async function convertProcessedAudio(source: Blob, format: ProcessedFormat) {
  const { Input, ALL_FORMATS, BlobSource, Output, BufferTarget, Mp3OutputFormat, WavOutputFormat, Mp4OutputFormat, Conversion, canEncodeAudio } = await import('mediabunny');
  if (format === 'mp3' && !(await canEncodeAudio('mp3'))) { const { registerMp3Encoder } = await import('@mediabunny/mp3-encoder'); registerMp3Encoder(); }
  if (format === 'm4a' && !(await canEncodeAudio('aac'))) throw new Error('AAC encoder unavailable');
  const target = new BufferTarget(); const input = new Input({ source: new BlobSource(source), formats: ALL_FORMATS });
  const output = new Output({format: format === 'mp3' ? new Mp3OutputFormat() : format === 'wav' ? new WavOutputFormat() : new Mp4OutputFormat(),target});
  const conversion = await Conversion.init({input,output,video:{discard:true},audio:format==='mp3'?{bitrate:192_000,numberOfChannels:2,sampleRate:48_000,forceTranscode:true}:format==='wav'?{numberOfChannels:2,sampleRate:48_000,sampleFormat:'s16',forceTranscode:true}:{codec:'aac',bitrate:128_000,numberOfChannels:2,sampleRate:48_000,forceTranscode:true},copy:false,showWarnings:false});
  if (!conversion.isValid) throw new Error(`Không hỗ trợ ${format.toUpperCase()} trên thiết bị này.`); await conversion.execute(); if (!target.buffer) throw new Error(`Không tạo được ${format.toUpperCase()}.`); return new Blob([target.buffer], { type: format === 'mp3' ? 'audio/mpeg' : format === 'wav' ? 'audio/wav' : 'audio/mp4' });
}
