'use client';
import {useEffect,useState} from 'react';
import {Download,FileJson,FileText,Image as ImageIcon,Music2,Video} from 'lucide-react';
import type {Song} from '@/components/v4/types';
import {convertProcessedAudio,renderTikTokLikeAudio} from '@/app/lib/audio-processing';
import {buildEstimatedKaraokeTimeline,exportSrt,type KaraokeLine} from '@/app/lib/karaoke';
import {cleanLyricsForVideo} from '@/components/v4/lyrics-clean';
function saveBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function name(value:string){return(value||'suno').replace(/[\\/:*?"<>|]+/g,'-').trim().slice(0,120)||'suno'}
function isSunoUrl(value:string){try{const u=new URL(value);return u.protocol==='https:'&&(u.hostname==='suno.com'||u.hostname.endsWith('.suno.com'))}catch{return false}}
export function V5DownloadEnhancer(){const[song,setSong]=useState<Song|null>(null),[sourceUrl,setSourceUrl]=useState(''),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[karaokeTimeline,setKaraokeTimeline]=useState<KaraokeLine[]>([]);
useEffect(()=>{let timer:number|undefined,controller:AbortController|null=null;const sync=()=>{const input=document.querySelector<HTMLInputElement>('input[placeholder^="Dán liên kết Suno"]');if(!input)return;const value=input.value.trim();if(!isSunoUrl(value)||value===sourceUrl)return;if(timer)clearTimeout(timer);timer=window.setTimeout(async()=>{controller?.abort();controller=new AbortController();try{const res=await fetch('/api/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:value}),signal:controller.signal}),data=await res.json();if(!res.ok)return;setSong(data);setSourceUrl(value)}catch{}},300)};const onInput=()=>sync();document.addEventListener('input',onInput,true);sync();return()=>{document.removeEventListener('input',onInput,true);controller?.abort();if(timer)clearTimeout(timer)}},[sourceUrl]);
useEffect(()=>{const onTimeline=(event:Event)=>{const detail=(event as CustomEvent<KaraokeLine[]>).detail;if(Array.isArray(detail))setKaraokeTimeline(detail)};window.addEventListener('suno-karaoke-timeline-change',onTimeline);return()=>window.removeEventListener('suno-karaoke-timeline-change',onTimeline)},[]);
async function fetchAndSave(url:string,filename:string){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error('Không tải được tệp.');saveBlob(await res.blob(),filename)}
async function audio(format:'m4a'|'mp3'|'wav'){if(!song)return;setBusy(format);setError('');try{const res=await fetch(song.audio,{cache:'no-store'});if(!res.ok)throw Error('Không tải được âm thanh.');const source=await res.blob();if(format==='m4a'){saveBlob(source,`${name(song.title)}.${format}`)}else{const processed=await renderTikTokLikeAudio(source),blob=await convertProcessedAudio(processed,format);saveBlob(blob,`${name(song.title)}-processed.${format}`)}}catch(e){setError(e instanceof Error?e.message:'Không tải được âm thanh.')}finally{setBusy(null)}}
async function originalVideo(){if(!song?.video)return;setBusy('video');setError('');try{await fetchAndSave(song.video,`${name(song.title)}-original.mp4`)}catch(e){setError(e instanceof Error?e.message:'Không tải được video gốc.')}finally{setBusy(null)}}
async function cover(){if(!song?.picture)return;setBusy('cover');try{const res=await fetch(song.picture,{cache:'no-store'});if(!res.ok)throw Error('Không tải được ảnh bìa.');const blob=await res.blob(),ext=blob.type.includes('png')?'png':blob.type.includes('webp')?'webp':'jpg';saveBlob(blob,`${name(song.title)}-cover.${ext}`)}catch(e){setError(e instanceof Error?e.message:'Không tải được ảnh bìa.')}finally{setBusy(null)}}
function lyrics(){if(song?.lyrics)saveBlob(new Blob([song.lyrics],{type:'text/plain;charset=utf-8'}),`${name(song.title)}-lyrics.txt`)}function srt(){if(!song?.lyrics||!song.duration)return;const clean=cleanLyricsForVideo(song.lyrics),timeline=karaokeTimeline.length?karaokeTimeline:buildEstimatedKaraokeTimeline(clean,song.duration);saveBlob(new Blob([exportSrt(timeline)],{type:'application/x-subrip;charset=utf-8'}),`${name(song.title)}-lyrics.srt`)}function metadata(){if(song)saveBlob(new Blob([JSON.stringify({title:song.title,creator:song.creator,description:song.description,style:song.style,tags:song.tags,duration:song.duration,sourceUrl},null,2)],{type:'application/json;charset=utf-8'}),`${name(song.title)}-metadata.json`)}
if(!song)return null;return <section id="song-downloads" className="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/[.045] p-4"><div className="flex items-center gap-2"><Download className="size-4 text-cyan-300"/><div><p className="font-bold">Tải xuống</p><p className="text-xs text-white/45">Âm thanh, video gốc và dữ liệu bài hát.</p></div></div>{error&&<p className="mt-3 text-xs text-rose-200">{error}</p>}<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><button onClick={()=>audio('mp3')} disabled={!!busy} className="rounded-xl bg-violet-500 px-3 py-3 text-sm font-bold disabled:opacity-45">{busy==='mp3'?'Đang tạo…':'Tải MP3 đã xử lý'}</button><button onClick={()=>audio('wav')} disabled={!!busy} className="rounded-xl bg-white/10 px-3 py-3 text-sm font-bold disabled:opacity-45">{busy==='wav'?'Đang tạo…':'Tải WAV đã xử lý'}</button><button onClick={()=>audio('m4a')} disabled={!!busy} className="rounded-xl bg-white/10 px-3 py-3 text-sm font-bold disabled:opacity-45"><Music2 className="mr-1 inline size-4"/>M4A</button><button onClick={originalVideo} disabled={!song.video||!!busy} className="rounded-xl bg-cyan-400/10 px-3 py-3 text-sm font-bold disabled:opacity-30"><Video className="mr-1 inline size-4"/>{busy==='video'?'Đang tải…':'Video gốc'}</button><button onClick={cover} disabled={!song.picture||!!busy} className="rounded-xl bg-white/10 px-3 py-3 text-sm font-bold disabled:opacity-30"><ImageIcon className="mr-1 inline size-4"/>Ảnh bìa</button><button onClick={lyrics} disabled={!song.lyrics} className="rounded-xl bg-white/10 px-3 py-3 text-sm font-bold disabled:opacity-30"><FileText className="mr-1 inline size-4"/>Lời bài hát</button><button onClick={srt} disabled={!song.lyrics||!song.duration} className="rounded-xl bg-white/10 px-3 py-3 text-sm font-bold disabled:opacity-30"><FileText className="mr-1 inline size-4"/>SRT lyrics</button><button onClick={metadata} className="rounded-xl bg-white/10 px-3 py-3 text-sm font-bold"><FileJson className="mr-1 inline size-4"/>Thông tin bài hát</button></div></section>}
