'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {Pause,Play,RotateCcw,Scissors} from 'lucide-react';
import {AudioFadeEditor} from './audio-fade-editor';

type Trim={start:number;end:number;duration:number};
const EVENT='suno-v10-audio-trim-change';
const KEY='suno-v10-audio-trim';
function fmt(v:number){const s=Math.max(0,Math.round(v*10)/10);return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}.${Math.round((s%1)*10)}`}
function emit(trim:Trim){window.dispatchEvent(new CustomEvent(EVENT,{detail:trim}))}

export function AudioTrimEditor(){
 const audio=useRef<HTMLAudioElement|null>(null);const [src,setSrc]=useState('');const [duration,setDuration]=useState(0);const [start,setStart]=useState(0);const [end,setEnd]=useState(0);const [playing,setPlaying]=useState(false);const [current,setCurrent]=useState(0);
 useEffect(()=>{const sync=()=>{const el=document.querySelector('.mobile-song-head audio') as HTMLAudioElement|null;if(!el?.src)return;setSrc(el.src);const d=Number(el.duration)||0;if(d>0){setDuration(d);setEnd(v=>v>0?Math.min(v,d):d)}};sync();const id=window.setInterval(sync,800);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{if(!duration)return;try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);const s=Math.max(0,Math.min(duration,Number(v.start)||0)),e=Math.max(s+.1,Math.min(duration,Number(v.end)||duration));setStart(s);setEnd(e);emit({start:s,end:e,duration})}else emit({start:0,end:duration,duration})}catch{emit({start:0,end:duration,duration})}},[duration]);
 useEffect(()=>{if(!duration)return;const t={start,end:end||duration,duration};localStorage.setItem(KEY,JSON.stringify(t));emit(t)},[start,end,duration]);
 useEffect(()=>{const el=audio.current;if(!el)return;const time=()=>{setCurrent(el.currentTime);if(el.currentTime>=end-.03){el.pause();setPlaying(false);el.currentTime=start;setCurrent(start)}};const stop=()=>setPlaying(false);el.addEventListener('timeupdate',time);el.addEventListener('pause',stop);return()=>{el.removeEventListener('timeupdate',time);el.removeEventListener('pause',stop)}},[start,end,src]);
 const span=Math.max(.1,end-start),left=duration?start/duration*100:0,width=duration?span/duration*100:100;
 const ticks=useMemo(()=>Array.from({length:48},(_,i)=>22+Math.abs(Math.sin(i*1.73))*54),[]);
 function changeStart(v:number){const n=Math.max(0,Math.min(Number(v),end-.1));setStart(n);if(audio.current&&audio.current.currentTime<n)audio.current.currentTime=n}
 function changeEnd(v:number){const n=Math.min(duration,Math.max(Number(v),start+.1));setEnd(n);if(audio.current&&audio.current.currentTime>n)audio.current.currentTime=start}
 async function toggle(){const el=audio.current;if(!el||!src)return;if(playing){el.pause();return}if(el.currentTime<start||el.currentTime>=end)el.currentTime=start;try{await el.play();setPlaying(true)}catch{}}
 function reset(){setStart(0);setEnd(duration);if(audio.current){audio.current.pause();audio.current.currentTime=0}}
 return <><section className="rounded-2xl border border-white/[.08] bg-[#0b1626] p-4"><audio ref={audio} src={src} preload="metadata"/><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-300">Audio Trim Editor</p><b className="text-sm">Cắt đoạn âm thanh trước khi xuất</b></div><button onClick={reset} disabled={!duration} className="rounded-lg bg-white/[.06] p-2 text-white/55 disabled:opacity-30" title="Đặt lại"><RotateCcw className="size-4"/></button></div>{!duration?<p className="mt-3 text-xs text-white/35">Dán và tải bài Suno để chỉnh điểm bắt đầu/kết thúc.</p>:<><div className="relative mt-4 h-20 overflow-hidden rounded-xl border border-white/[.06] bg-black/25 px-2"><div className="flex h-full items-center gap-[3px]">{ticks.map((h,i)=><i key={i} className="block flex-1 rounded-full bg-white/15" style={{height:`${h}%`}}/>)}</div><div className="pointer-events-none absolute inset-y-0 border-x border-cyan-300/80 bg-cyan-300/10" style={{left:`${left}%`,width:`${width}%`}}/><div className="pointer-events-none absolute bottom-0 top-0 w-px bg-white/70" style={{left:`${duration?current/duration*100:0}%`}}/></div><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-end gap-3"><label className="text-[10px] text-white/40">Start<input type="number" min="0" max={Math.max(0,end-.1)} step="0.1" value={start.toFixed(1)} onChange={e=>changeStart(Number(e.target.value))} className="mt-1 h-9 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-xs text-white"/></label><button onClick={toggle} className="grid size-10 place-items-center rounded-full bg-cyan-300 text-[#07111d]">{playing?<Pause className="size-4"/>:<Play className="ml-0.5 size-4"/>}</button><label className="text-[10px] text-white/40">End<input type="number" min={start+.1} max={duration} step="0.1" value={end.toFixed(1)} onChange={e=>changeEnd(Number(e.target.value))} className="mt-1 h-9 w-full rounded-lg border border-white/10 bg-black/20 px-2 text-xs text-white"/></label></div><div className="mt-3"><input aria-label="Trim start" type="range" min="0" max={Math.max(0,end-.1)} step="0.1" value={start} onChange={e=>changeStart(Number(e.target.value))} className="w-full accent-cyan-300"/><input aria-label="Trim end" type="range" min={start+.1} max={duration} step="0.1" value={end} onChange={e=>changeEnd(Number(e.target.value))} className="mt-1 w-full accent-violet-300"/></div><div className="mt-2 flex items-center justify-between text-[10px] text-white/35"><span>{fmt(start)}</span><span className="flex items-center gap-1 font-semibold text-cyan-200"><Scissors className="size-3"/>{fmt(span)} selected</span><span>{fmt(end)}</span></div></>}</section><AudioFadeEditor/></>;
}
