'use client';

import {useEffect,useMemo,useState} from 'react';

export type AudioPresetId='original'|'balanced'|'warm'|'punch'|'vocal'|'tiktok';
export type AudioPreset={id:AudioPresetId;label:string;description:string;low:number;mid:number;high:number;compressor:{threshold:number;knee:number;ratio:number;attack:number;release:number};gain:number};
export const AUDIO_PRESETS:AudioPreset[]=[
{id:'original',label:'Original',description:'Giữ nguyên âm thanh gốc',low:0,mid:0,high:0,compressor:{threshold:0,knee:0,ratio:1,attack:.003,release:.25},gain:0},
{id:'balanced',label:'Balanced',description:'Cân bằng, sạch và dễ nghe',low:1,mid:0,high:1.2,compressor:{threshold:-18,knee:12,ratio:2.2,attack:.012,release:.22},gain:-.5},
{id:'warm',label:'Warm',description:'Ấm hơn, bớt chói',low:2.2,mid:.6,high:-1.8,compressor:{threshold:-20,knee:16,ratio:2,attack:.018,release:.3},gain:-.8},
{id:'punch',label:'Punch',description:'Bass và nhịp chắc hơn',low:3,mid:-.8,high:1,compressor:{threshold:-22,knee:10,ratio:3.2,attack:.008,release:.16},gain:-1.2},
{id:'vocal',label:'Vocal',description:'Làm rõ giọng hát',low:-1.2,mid:2.5,high:1.4,compressor:{threshold:-21,knee:14,ratio:2.8,attack:.01,release:.2},gain:-.8},
{id:'tiktok',label:'Social',description:'Dày, rõ trên loa điện thoại',low:1.2,mid:1.8,high:1.6,compressor:{threshold:-24,knee:10,ratio:3.5,attack:.006,release:.14},gain:-1.5},
];
const KEY='sunodown-v10-audio-preset';
export function loadAudioPresetId():AudioPresetId{if(typeof window==='undefined')return'original';const v=localStorage.getItem(KEY) as AudioPresetId|null;return AUDIO_PRESETS.some(x=>x.id===v)?v!:'original'}
export function getAudioPreset(id:AudioPresetId){return AUDIO_PRESETS.find(x=>x.id===id)||AUDIO_PRESETS[0]}
export async function processAudioBlob(input:Blob,presetId:AudioPresetId,onProgress?:(n:number)=>void){if(presetId==='original')return input;const data=await input.arrayBuffer();onProgress?.(10);const ctx=new AudioContext();try{const decoded=await ctx.decodeAudioData(data.slice(0));onProgress?.(25);const preset=getAudioPreset(presetId);const offline=new OfflineAudioContext(decoded.numberOfChannels,decoded.length,decoded.sampleRate);const source=offline.createBufferSource();source.buffer=decoded;const low=offline.createBiquadFilter();low.type='lowshelf';low.frequency.value=180;low.gain.value=preset.low;const mid=offline.createBiquadFilter();mid.type='peaking';mid.frequency.value=1800;mid.Q.value=.8;mid.gain.value=preset.mid;const high=offline.createBiquadFilter();high.type='highshelf';high.frequency.value=6500;high.gain.value=preset.high;const comp=offline.createDynamicsCompressor();Object.assign(comp.threshold,{value:preset.compressor.threshold});comp.knee.value=preset.compressor.knee;comp.ratio.value=preset.compressor.ratio;comp.attack.value=preset.compressor.attack;comp.release.value=preset.compressor.release;const gain=offline.createGain();gain.gain.value=Math.pow(10,preset.gain/20);source.connect(low).connect(mid).connect(high).connect(comp).connect(gain).connect(offline.destination);source.start();const rendered=await offline.startRendering();onProgress?.(80);return encodeWav(rendered)}finally{await ctx.close()}}
function encodeWav(buffer:AudioBuffer){const channels=buffer.numberOfChannels,samples=buffer.length,rate=buffer.sampleRate,bytes=44+samples*channels*2,out=new ArrayBuffer(bytes),v=new DataView(out);let p=0;const str=(s:string)=>{for(const c of s)v.setUint8(p++,c.charCodeAt(0))};str('RIFF');v.setUint32(p,bytes-8,true);p+=4;str('WAVEfmt ');v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,channels,true);p+=2;v.setUint32(p,rate,true);p+=4;v.setUint32(p,rate*channels*2,true);p+=4;v.setUint16(p,channels*2,true);p+=2;v.setUint16(p,16,true);p+=2;str('data');v.setUint32(p,samples*channels*2,true);p+=4;for(let i=0;i<samples;i++)for(let c=0;c<channels;c++){const s=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(p,s<0?s*32768:s*32767,true);p+=2}return new Blob([out],{type:'audio/wav'})}
export function AudioProcessingPresets(){const [id,setId]=useState<AudioPresetId>('original');useEffect(()=>setId(loadAudioPresetId()),[]);const active=useMemo(()=>getAudioPreset(id),[id]);const choose=(next:AudioPresetId)=>{setId(next);localStorage.setItem(KEY,next);window.dispatchEvent(new CustomEvent('sunodown-v10-audio-preset',{detail:next}))};return <section className="rounded-2xl border border-white/[.06] bg-white/[.02] p-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-emerald-300">Audio processing</p><div className="mt-3 flex snap-x gap-2 overflow-x-auto pb-2">{AUDIO_PRESETS.map(x=><button key={x.id} onClick={()=>choose(x.id)} className={`shrink-0 rounded-xl px-3 py-2 text-xs ${id===x.id?'bg-emerald-400/20 ring-1 ring-emerald-300/30':'bg-white/5'}`}>{x.label}</button>)}</div><p className="mt-2 text-xs text-white/45">{active.description} · EQ {active.low>0?'+':''}{active.low}/{active.mid>0?'+':''}{active.mid}/{active.high>0?'+':''}{active.high} dB · Comp {active.compressor.ratio}:1</p></section>}
