'use client';

import type {Song} from '../v4/types';
import type {SafeRenderOptions} from '../v4/renderer-safe';
import {convertProcessedAudio,renderLoopedFadeAudio} from '@/app/lib/audio-processing';

type Fade={fadeIn:number;fadeOut:number};
function readFade():Fade{try{const v=JSON.parse(localStorage.getItem('suno-v10-audio-fade')||'null');return{fadeIn:Math.max(0,Math.min(30,Number(v?.fadeIn)||0)),fadeOut:Math.max(0,Math.min(30,Number(v?.fadeOut)||0))}}catch{return{fadeIn:0,fadeOut:0}}}
function readTrim(duration:number){try{const v=JSON.parse(localStorage.getItem('suno-v10-audio-trim')||'null');const start=Math.max(0,Math.min(duration,Number(v?.start)||0)),end=Math.max(start+.05,Math.min(duration,Number(v?.end)||duration));return{start,end}}catch{return{start:0,end:duration}}}
export function hasAudioFade(){const f=readFade();return f.fadeIn>.001||f.fadeOut>.001}

export async function applyAudioFadeToRenderedVideo(video:Blob,song:Song,options:SafeRenderOptions){
 const fade=readFade();if(fade.fadeIn<=.001&&fade.fadeOut<=.001)return video;const response=await fetch(song.audio,{cache:'no-store'});if(!response.ok)throw new Error('Không tải được audio để áp dụng fade.');const source=await response.blob();const {Input,ALL_FORMATS,BlobSource,EncodedPacketSink,EncodedAudioPacketSource,EncodedVideoPacketSource,Output,BufferTarget,Mp4OutputFormat}=await import('mediabunny');const sourceInput=new Input({source:new BlobSource(source),formats:ALL_FORMATS}),sourceDuration=await sourceInput.computeDuration(),trim=readTrim(sourceDuration),clipDuration=Math.max(.05,trim.end-trim.start),totalDuration=Math.max(clipDuration,Number(options.loopDuration)||clipDuration),start=Math.max(0,Number(options.startSeconds)||0),duration=Math.max(.05,Math.min(Number(options.previewSeconds)||totalDuration,totalDuration-start));
 const fadedWav=await renderLoopedFadeAudio(source,trim.start,trim.end,start,duration,totalDuration,fade.fadeIn,fade.fadeOut);let faded:Blob;try{faded=await convertProcessedAudio(fadedWav,'m4a')}catch{faded=await convertProcessedAudio(fadedWav,'mp3')}
 const videoInput=new Input({source:new BlobSource(video),formats:ALL_FORMATS}),fadedInput=new Input({source:new BlobSource(faded),formats:ALL_FORMATS}),videoTrack=await videoInput.getPrimaryVideoTrack(),audioTrack=await fadedInput.getPrimaryAudioTrack();if(!videoTrack||!audioTrack)throw new Error('Không đọc được track để ghép fade.');const [videoCodec,audioCodec,videoConfig,audioConfig]=await Promise.all([videoTrack.getCodec(),audioTrack.getCodec(),videoTrack.getDecoderConfig(),audioTrack.getDecoderConfig()]);if(!videoCodec||!audioCodec||!videoConfig||!audioConfig)throw new Error('Codec không hỗ trợ ghép fade.');const target=new BufferTarget(),output=new Output({format:new Mp4OutputFormat(),target}),videoOut=new EncodedVideoPacketSource(videoCodec),audioOut=new EncodedAudioPacketSource(audioCodec);output.addVideoTrack(videoOut,{decoderConfig:videoConfig});output.addAudioTrack(audioOut,{decoderConfig:audioConfig});await output.start();const videoSink=new EncodedPacketSink(videoTrack),audioSink=new EncodedPacketSink(audioTrack);for await(const packet of videoSink.packets())await videoOut.add(packet,{decoderConfig:videoConfig});for await(const packet of audioSink.packets())await audioOut.add(packet,{decoderConfig:audioConfig});await output.finalize();if(!target.buffer)throw new Error('Không ghép được Fade In / Fade Out.');return new Blob([target.buffer],{type:'video/mp4'})
}
