'use client';

import {useEffect,useMemo,useState} from 'react';
import {Clock3,Search,Trash2,X} from 'lucide-react';
import type {Song} from '../v4/types';

export type LibraryEvent='resolved'|'downloaded'|'rendered';
export type LibraryItem={id:string;url:string;title:string;creator:string;picture?:string;duration?:number;lastEvent:LibraryEvent;updatedAt:number;events:Partial<Record<LibraryEvent,number>>};
const KEY='sunodown-v10-local-library';
const LIMIT=100;

function read():LibraryItem[]{if(typeof window==='undefined')return [];try{const value=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(value)?value.slice(0,LIMIT):[]}catch{return []}}
function write(items:LibraryItem[]){localStorage.setItem(KEY,JSON.stringify(items.slice(0,LIMIT)));window.dispatchEvent(new CustomEvent('sunodown-v10-library-change'))}
export function recordLibraryItem(url:string,song:Song,event:LibraryEvent){if(typeof window==='undefined'||!url)return;const items=read(),now=Date.now(),id=String(song.id||url),old=items.find(x=>x.id===id||x.url===url);const next:LibraryItem={id,url,title:song.title||old?.title||'Suno',creator:song.creator||old?.creator||'',picture:song.picture||old?.picture,duration:song.duration||old?.duration,lastEvent:event,updatedAt:now,events:{...old?.events,[event]:now}};write([next,...items.filter(x=>x.id!==id&&x.url!==url)].sort((a,b)=>b.updatedAt-a.updatedAt))}
const eventLabel:Record<LibraryEvent,string>={resolved:'Đã mở',downloaded:'Đã tải',rendered:'Đã render'};
export function LocalLibrary({onOpen}:{onOpen:(url:string)=>void}){const [items,setItems]=useState<LibraryItem[]>([]),[query,setQuery]=useState(''),[event,setEvent]=useState<'all'|LibraryEvent>('all');const refresh=()=>setItems(read());useEffect(()=>{refresh();window.addEventListener('sunodown-v10-library-change',refresh);return()=>window.removeEventListener('sunodown-v10-library-change',refresh)},[]);const shown=useMemo(()=>items.filter(x=>(event==='all'||x.events[event])&&(!query||`${x.title} ${x.creator}`.toLowerCase().includes(query.toLowerCase()))),[items,event,query]);const remove=(id:string)=>{write(items.filter(x=>x.id!==id));refresh()};const clear=()=>{localStorage.removeItem(KEY);refresh()};return <details className="mt-4 rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><summary className="cursor-pointer text-sm font-bold"><Clock3 className="mr-2 inline size-4"/>Thư viện / Lịch sử <span className="text-white/35">({items.length})</span></summary><div className="mt-3 flex flex-wrap gap-2"><label className="relative min-w-52 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-white/30"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm bài hát..." className="w-full rounded-xl border border-white/10 bg-black/20 py-2 pl-9 pr-3 text-xs"/></label>{(['all','resolved','downloaded','rendered'] as const).map(x=><button key={x} onClick={()=>setEvent(x)} className={`rounded-lg px-3 py-2 text-xs ${event===x?'bg-violet-400/20':'bg-white/5'}`}>{x==='all'?'Tất cả':eventLabel[x]}</button>)}{items.length>0&&<button onClick={clear} className="rounded-lg bg-red-400/10 px-3 py-2 text-xs text-red-200">Xóa lịch sử</button>}</div><div className="mt-3 grid max-h-80 gap-2 overflow-auto">{shown.map(item=><div key={item.id} className="flex items-center gap-3 rounded-xl bg-black/20 p-2">{item.picture?<img src={item.picture} alt="" className="size-11 rounded-lg object-cover"/>:<div className="size-11 rounded-lg bg-white/5"/>}<button onClick={()=>onOpen(item.url)} className="min-w-0 flex-1 text-left"><p className="truncate text-xs font-bold">{item.title}</p><p className="truncate text-[10px] text-white/35">{item.creator||eventLabel[item.lastEvent]} · {new Date(item.updatedAt).toLocaleString()}</p></button><button onClick={()=>remove(item.id)} aria-label="Xóa khỏi lịch sử" className="rounded-lg p-2 text-white/35 hover:bg-white/5"><X className="size-4"/></button></div>)}{shown.length===0&&<p className="py-5 text-center text-xs text-white/35">Chưa có bài phù hợp.</p>}</div><p className="mt-2 text-[10px] text-white/25">Lưu tối đa {LIMIT} bài trên thiết bị này; chỉ lưu metadata, không lưu file audio/video để tránh đầy bộ nhớ mobile.</p></details>}
