'use client';

import {useEffect,useRef,useState} from 'react';
import {Activity,LoaderCircle} from 'lucide-react';

type Meter={lufs:number;truePeak:number;duration:number};
function findAudio(){return [...document.querySelectorAll('audio')].find(a=>a.src) as HTMLAudioElement|undefined}
function db(v:number){return 20*Math.log10(Math.max(v,1e-12))}
function biquadHighpass(x:Float32Array,sr:number){const f=38,q=.5,w=2*Math.PI*f/sr,alpha=Math.sin(w)/(2*q),c=Math.cos(w),a0=1+alpha,b0=(1+c)/2,b1=-(1+c),b2=b0,a1=-2*c,a2=1-alpha;const y=new Float32Array(x.length);let x1=0,x2=0,y1=0,y2=0;for(let i=0;i<x.length;i++){const v=(b0*x[i]+b1*x1+b2*x2-a1*y1-a2*y2)/a0;y[i]=v;x2=x1;x1=x[i];y2=y1;y1=v}return y}
function biquadShelf(x:Float32Array,sr:number){const f=1681.974,g=3.999843,A=Math.pow(10,g/40),w=2*Math.PI*f/sr,c=Math.cos(w),s=Math.sin(w),alpha=s/2*Math.SQRT2,beta=2*Math.sqrt(A)*alpha;const b0=A*((A+1)+(A-1)*c+beta),b1=-2*A*((A-1)+(A+1)*c),b2=A*((A+1)+(A-1)*c-beta),a0=(A+1)-(A-1)*c+beta,a1=2*((A-1)-(A+1)*c),a2=(A+1)-(A-1)*c-beta;const y=new Float32Array(x.length);let x1=0,x2=0,y1=0,y2=0;for(let i=0;i<x.length;i++){const v=(b0*x[i]+b1*x1+b2*x2-a1*y1-a2*y2)/a0;y[i]=v;x2=x1;x1=x[i];y2=y1;y1=v}return y}
function channelEnergy(data:Float32Array,sr:number){const y=biquadShelf(biquadHighpass(data,sr),sr),block=Math.max(1,Math.round(sr*.4)),step=Math.max(1,Math.round(sr*.1)),out:number[]=[];for(let p=0;p+block<=y.length;p+=step){let e=0;for(let i=p;i<p+block;i++)e+=y[i]*y[i];out.push(e/block)}return out}
function integratedLufs(buffer:AudioBuffer){const energies:Array<number[]>=[];for(let c=0;c<buffer.numberOfChannels;c++)energies.push(channelEnergy(buffer.getChannelData(c),buffer.sampleRate));const n=Math.min(...energies.map(x=>x.length));let blocks:number[]=[];for(let i=0;i<n;i++){let e=0;for(let c=0;c<energies.length;c++)e+=energies[c][i]*(c>=3?1.41:1);blocks.push(e)}const loud=(e:number)=>-0.691+10*Math.log10(Math.max(e,1e-15));blocks=blocks.filter(e=>loud(e)>-70);if(!blocks.length)return -Infinity;let mean=blocks.reduce((a,b)=>a+b,0)/blocks.length,relative=loud(mean)-10;blocks=blocks.filter(e=>loud(e)>relative);mean=blocks.reduce((a,b)=>a+b,0)/Math.max(1,blocks.length);return loud(mean)}
function truePeak(buffer:AudioBuffer){let peak=0;for(let c=0;c<buffer.numberOfChannels;c++){const x=buffer.getChannelData(c);for(let i=0;i<x.length-1;i++){const a=x[i],b=x[i+1];for(let k=0;k<4;k++){const t=k/4,v=a+(b-a)*t;peak=Math.max(peak,Math.abs(v))}}}return db(peak)}
async function analyze(src:string,signal:AbortSignal){const r=await fetch(src,{signal});if(!r.ok)throw new Error('Không tải được audio để đo.');const bytes=await r.arrayBuffer();const ctx=new AudioContext();try{const b=await ctx.decodeAudioData(bytes.slice(0));return {lufs:integratedLufs(b),truePeak:truePeak(b),duration:b.duration}}finally{void ctx.close()}}
export function V10LoudnessMeter(){const [meter,setMeter]=useState<Meter|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),last=useRef('');useEffect(()=>{let controller:AbortController|null=null,timer=0;const scan=()=>{clearTimeout(timer);timer=window.setTimeout(async()=>{const audio=findAudio(),src=audio?.src||'';if(!src||src===last.current)return;last.current=src;controller?.abort();controller=new AbortController();setBusy(true);setError('');try{setMeter(await analyze(src,controller.signal))}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Không đo được audio.')}finally{if(!controller.signal.aborted)setBusy(false)}},500)};const o=new MutationObserver(scan);o.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['src']});scan();return()=>{clearTimeout(timer);controller?.abort();o.disconnect()}},[]);return <section className="mt-5 rounded-2xl border border-cyan-300/10 bg-[#081421] p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-cyan-300">Audio Meter · V10</p><h2 className="mt-1 font-bold"><Activity className="mr-2 inline size-4"/>LUFS / True Peak</h2></div>{busy&&<LoaderCircle className="size-5 animate-spin text-cyan-300"/>}</div>{meter?<div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-black/20 p-4"><p className="text-[10px] uppercase text-white/35">Integrated loudness</p><p className="mt-1 text-2xl font-bold">{Number.isFinite(meter.lufs)?meter.lufs.toFixed(1):'−∞'} <span className="text-xs text-white/35">LUFS</span></p></div><div className="rounded-xl bg-black/20 p-4"><p className="text-[10px] uppercase text-white/35">True peak · 4×</p><p className="mt-1 text-2xl font-bold">{meter.truePeak.toFixed(1)} <span className="text-xs text-white/35">dBTP</span></p></div></div>:<p className="mt-3 text-xs text-white/35">{busy?'Đang phân tích toàn bộ audio…':error||'Mở một bài Suno để đo loudness.'}</p>}<p className="mt-3 text-[10px] leading-4 text-white/25">Integrated LUFS dùng K-weighting + absolute/relative gating theo ITU-R BS.1770/EBU R128. True Peak quét nội mẫu 4×; xử lý cục bộ trên trình duyệt, không upload audio.</p></section>}
