'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';

type SafeZonePlatform='tiktok'|'reels'|'shorts';
type SafeZoneConfig={enabled:boolean;platform:SafeZonePlatform;opacity:number};
const KEY='suno-v10-safe-zone';
const DEFAULT:SafeZoneConfig={enabled:false,platform:'tiktok',opacity:.62};
const META:Record<SafeZonePlatform,{label:string;top:number;bottom:number;left:number;right:number;note:string}>={
 tiktok:{label:'TikTok',top:10,bottom:21,left:6,right:17,note:'Chừa vùng avatar/action bên phải và caption phía dưới.'},
 reels:{label:'Reels',top:9,bottom:20,left:6,right:8,note:'Chừa header và vùng caption/control phía dưới.'},
 shorts:{label:'Shorts',top:8,bottom:19,left:6,right:16,note:'Chừa action rail bên phải và metadata phía dưới.'}
};
function read(){if(typeof window==='undefined')return DEFAULT;try{return{...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')} as SafeZoneConfig}catch{return DEFAULT}}
export function SafeZoneOverlay(){const[c,setC]=useState(DEFAULT),[host,setHost]=useState<HTMLElement|null>(null);useEffect(()=>{setC(read());const find=()=>setHost(document.querySelector('canvas[aria-label="Xem trước video đồng bộ cùng âm thanh"]')?.parentElement||null);find();const o=new MutationObserver(find);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);const update=(p:Partial<SafeZoneConfig>)=>{const n={...c,...p};setC(n);localStorage.setItem(KEY,JSON.stringify(n))};const m=META[c.platform];const overlay=host&&c.enabled?createPortal(<div className="pointer-events-none absolute inset-0 z-40" aria-label={`${m.label} safe zone`}><div className="absolute inset-0" style={{background:`linear-gradient(to bottom,rgba(239,68,68,${c.opacity*.42}) 0 ${m.top}%,transparent ${m.top}% ${100-m.bottom}%,rgba(239,68,68,${c.opacity*.42}) ${100-m.bottom}% 100%)`}}/><div className="absolute border border-dashed border-emerald-300/90" style={{left:`${m.left}%`,right:`${m.right}%`,top:`${m.top}%`,bottom:`${m.bottom}%`,boxShadow:'0 0 0 9999px rgba(0,0,0,.08)'}}><span className="absolute left-1 top-1 rounded bg-emerald-400/90 px-1.5 py-0.5 text-[8px] font-bold text-black">SAFE · {m.label}</span></div><div className="absolute bg-red-400/15" style={{right:0,top:`${m.top}%`,bottom:`${m.bottom}%`,width:`${m.right}%`}}/></div>,host):null;return <>{overlay}<section className="mt-4 rounded-xl border border-emerald-300/10 bg-emerald-300/[.035] p-3"><div className="flex items-center justify-between gap-3"><div><b className="text-xs text-emerald-100">Safe Zone</b><p className="mt-1 text-[10px] text-white/35">TikTok / Reels / Shorts — guide chỉ ở preview, không burn vào video.</p></div><button type="button" onClick={()=>update({enabled:!c.enabled})} className={`min-h-10 rounded-lg px-3 text-xs font-bold ${c.enabled?'bg-emerald-300/20 text-emerald-100':'bg-white/5 text-white/55'}`}>{c.enabled?'Đang hiện':'Hiện guide'}</button></div>{c.enabled&&<div className="mt-3 grid gap-3"><div className="grid grid-cols-3 gap-2">{(Object.keys(META) as SafeZonePlatform[]).map(id=><button type="button" key={id} onClick={()=>update({platform:id})} className={`min-h-10 rounded-lg text-xs font-semibold ${c.platform===id?'bg-emerald-300/15 text-emerald-100 ring-1 ring-emerald-300/30':'bg-white/5 text-white/55'}`}>{META[id].label}</button>)}</div><p className="text-[10px] leading-4 text-white/45">{m.note} Vùng viền xanh là vùng an toàn khuyến nghị để đặt subtitle, logo và nội dung chính.</p><label className="text-[11px] text-white/45">Độ rõ guide <b className="float-right text-white">{Math.round(c.opacity*100)}%</b><input type="range" min="25" max="100" value={c.opacity*100} onChange={e=>update({opacity:+e.target.value/100})} className="mt-2 w-full accent-emerald-300"/></label></div>}</section></>}
