'use client';

import {useEffect,useState} from 'react';
import {CheckCircle2,LoaderCircle,Play,RotateCcw} from 'lucide-react';
import {renderTikTokCalibratedAudio,type TikTokCalibrationResult} from '@/app/lib/audio-processing';

function findAudio(){return [...document.querySelectorAll('audio')].find(a=>a.src) as HTMLAudioElement|undefined}
const KEY='sunodown-v10-tiktok-calibrated';

export function TikTokCalibratedProfile(){
 const [enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<TikTokCalibrationResult|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState('');
 useEffect(()=>{setEnabled(localStorage.getItem(KEY)==='1');return()=>{if(preview)URL.revokeObjectURL(preview)}},[]);
 const toggle=()=>{const next=!enabled;setEnabled(next);localStorage.setItem(KEY,next?'1':'0');window.dispatchEvent(new CustomEvent('sunodown-v10-tiktok-calibrated',{detail:next}))};
 const calibrate=async()=>{const audio=findAudio();if(!audio?.src)return setError('Mở một bài Suno trước khi hiệu chỉnh.');setBusy(true);setError('');try{const r=await fetch(audio.src);if(!r.ok)throw new Error('Không tải được audio.');const source=await r.blob();const out=await renderTikTokCalibratedAudio(source);if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(out.blob));setResult(out.metrics)}catch(e){setError(e instanceof Error?e.message:'Không hiệu chỉnh được audio.')}finally{setBusy(false)}};
 return <section className="rounded-2xl border border-fuchsia-300/15 bg-[#101223] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-fuchsia-300">TikTok Calibrated Profile</p><h3 className="mt-1 text-sm font-bold">Social master · −14 LUFS / −1 dBTP</h3><p className="mt-1 text-[11px] leading-5 text-white/40">48 kHz stereo, phone-speaker EQ, gentle compression và true-peak ceiling. Hiệu chỉnh gain theo loudness đo được thay vì gain cố định.</p></div><button onClick={toggle} className={`shrink-0 rounded-full px-3 py-2 text-[10px] font-bold ${enabled?'bg-fuchsia-400 text-black':'bg-white/5 text-white/55'}`}>{enabled?'ON':'OFF'}</button></div><button disabled={busy} onClick={calibrate} className="mt-3 w-full rounded-xl bg-fuchsia-400/15 px-3 py-2.5 text-xs font-bold text-fuchsia-100 disabled:opacity-40">{busy?<LoaderCircle className="mr-2 inline size-4 animate-spin"/>:<Play className="mr-2 inline size-4"/>}Phân tích & tạo bản calibrated</button>{result&&<div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-black/20 p-3"><span className="text-white/35">Before</span><b className="mt-1 block">{result.beforeLufs.toFixed(1)} LUFS</b><span className="text-[10px] text-white/30">{result.beforePeak.toFixed(1)} dBTP</span></div><div className="rounded-xl bg-black/20 p-3"><span className="text-white/35">After</span><b className="mt-1 block text-fuchsia-200">{result.afterLufs.toFixed(1)} LUFS</b><span className="text-[10px] text-white/30">{result.afterPeak.toFixed(1)} dBTP</span></div></div>}{preview&&<audio className="mt-3 w-full" controls src={preview}/>} {result&&<p className="mt-2 text-[10px] text-emerald-300"><CheckCircle2 className="mr-1 inline size-3"/>Gain correction {result.gainDb>=0?'+':''}{result.gainDb.toFixed(1)} dB · calibrated locally</p>}{error&&<p className="mt-2 text-[10px] text-amber-200"><RotateCcw className="mr-1 inline size-3"/>{error}</p>}</section>
}
