'use client';

import {useEffect,useRef,useState} from 'react';

type Result={bpm:number;confidence:number;beatSeconds:number;offset:number;beats:number[]};
type Props={audioUrl:string;duration:number;onSeek?:(seconds:number)=>void};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export const BEAT_GRID_KEY='suno-v10-beat-grid';
async function yieldUi(){await new Promise<void>(resolve=>setTimeout(resolve,0))}
async function detectBeat(buffer:AudioBuffer,onProgress:(v:number)=>void):Promise<Result>{
 const sampleRate=buffer.sampleRate,channels=buffer.numberOfChannels,hop=512,frame=1024,total=Math.floor((buffer.length-frame)/hop),maxFrames=18000,stride=Math.max(1,Math.ceil(total/maxFrames)),step=hop*stride,frames=Math.floor((buffer.length-frame)/step),envelope=new Float32Array(frames);let previous=0;
 for(let i=0;i<frames;i++){const from=i*step;let energy=0;for(let j=0;j<frame;j+=4){let mono=0;for(let ch=0;ch<channels;ch++)mono+=buffer.getChannelData(ch)[from+j]||0;mono/=channels;energy+=mono*mono}envelope[i]=Math.max(0,energy-previous*.92);previous=energy;if(i%500===0){onProgress(Math.round(i/Math.max(1,frames)*45));await yieldUi()}}
 let mean=0;for(const v of envelope)mean+=v;mean/=Math.max(1,envelope.length);for(let i=0;i<envelope.length;i++)envelope[i]=Math.max(0,envelope[i]-mean*.65);const envRate=sampleRate/step,minLag=Math.max(1,Math.floor(envRate*60/200)),maxLag=Math.min(envelope.length-2,Math.ceil(envRate*60/60));let bestLag=minLag,best=-Infinity;
 for(let lag=minLag;lag<=maxLag;lag++){let score=0,normA=0,normB=0;for(let i=lag;i<envelope.length;i++){const a=envelope[i],b=envelope[i-lag];score+=a*b;normA+=a*a;normB+=b*b}score/=Math.sqrt(Math.max(1e-9,normA*normB));const candidate=60*envRate/lag;if(candidate>=75&&candidate<=155)score*=1.035;if(score>best){best=score;bestLag=lag}if(lag%20===0){onProgress(45+Math.round((lag-minLag)/Math.max(1,maxLag-minLag)*35));await yieldUi()}}
 let bpm=60*envRate/bestLag;if(bpm>180)bpm/=2;if(bpm<70)bpm*=2;bpm=Math.round(bpm*10)/10;const beatSeconds=60/bpm,phaseSteps=Math.max(1,Math.round(beatSeconds*envRate)),phaseMax=Math.min(phaseSteps,envelope.length);let bestPhase=0,bestPhaseScore=-1;for(let phase=0;phase<phaseMax;phase++){let score=0;for(let i=phase;i<envelope.length;i+=phaseSteps)score+=envelope[i];if(score>bestPhaseScore){bestPhaseScore=score;bestPhase=phase}}const offset=bestPhase/envRate,beats:number[]=[];for(let t=offset;t<buffer.duration;t+=beatSeconds)beats.push(t);const confidence=clamp(Math.round(best*140),0,100);onProgress(100);return{bpm,confidence,beatSeconds,offset,beats};
}
export default function BeatBpmDetector({audioUrl,duration,onSeek}:Props){
 const [result,setResult]=useState<Result|null>(null),[progress,setProgress]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);const abort=useRef(0);
 useEffect(()=>{abort.current++;setResult(null);setProgress(0);setError('')},[audioUrl]);
 async function analyze(){const token=++abort.current;setBusy(true);setError('');setProgress(1);let ctx:AudioContext|null=null;try{const r=await fetch(audioUrl,{cache:'no-store'});if(!r.ok)throw new Error('Không tải được audio để phân tích BPM.');const AC=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AC)throw new Error('Trình duyệt không hỗ trợ AudioContext.');ctx=new AC();const buffer=await ctx.decodeAudioData(await r.arrayBuffer()),found=await detectBeat(buffer,setProgress);if(token===abort.current){setResult(found);const grid={bpm:found.bpm,offset:found.offset,confidence:found.confidence,audioUrl};localStorage.setItem(BEAT_GRID_KEY,JSON.stringify(grid));window.dispatchEvent(new CustomEvent('suno-beat-grid-change',{detail:grid}))}}catch(e){if(token===abort.current)setError(e instanceof Error?e.message:'Không phân tích được BPM.')}finally{if(ctx)void ctx.close().catch(()=>{});if(token===abort.current)setBusy(false)}}
 return <section className="mt-4 rounded-xl border border-violet-300/15 bg-violet-300/[.04] p-3"><div className="flex items-start justify-between gap-3"><div><b className="text-xs">Beat / BPM Detection</b><p className="mt-1 text-[10px] leading-4 text-white/40">Phân tích onset + autocorrelation trực tiếp trên thiết bị. Kết quả dùng được cho Beat-Synced Effects.</p></div><button type="button" disabled={busy} onClick={()=>void analyze()} className="min-h-10 shrink-0 rounded-lg bg-violet-400/15 px-3 py-2 text-xs font-bold text-violet-100 disabled:opacity-40">{busy?`${progress}%`:(result?'Phân tích lại':'Phân tích BPM')}</button></div>{busy&&<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-violet-300 transition-[width]" style={{width:`${progress}%`}}/></div>}{error&&<p className="mt-2 text-xs text-amber-200">{error}</p>}{result&&<><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-lg bg-black/20 p-2"><p className="text-[9px] uppercase text-white/35">BPM</p><b className="text-lg text-violet-100">{result.bpm}</b></div><div className="rounded-lg bg-black/20 p-2"><p className="text-[9px] uppercase text-white/35">Beat</p><b className="text-sm">{Math.round(result.beatSeconds*1000)} ms</b></div><div className="rounded-lg bg-black/20 p-2"><p className="text-[9px] uppercase text-white/35">Tin cậy</p><b className="text-sm">{result.confidence}%</b></div></div><div className="mt-3 overflow-x-auto pb-1"><div className="flex min-w-max gap-1">{result.beats.filter(t=>t<=duration).slice(0,96).map((t,i)=><button key={i} type="button" onClick={()=>onSeek?.(t)} title={`${t.toFixed(2)}s`} className="h-9 min-w-8 rounded-md bg-white/5 px-2 font-mono text-[9px] text-white/55 hover:bg-violet-300/15">{i+1}</button>)}</div></div><p className="mt-2 text-[10px] text-white/35">Beat đầu ~{result.offset.toFixed(2)}s · {result.beats.length} beat phát hiện. Chạm số beat để seek.</p></>}</section>
}
