'use client';

import {useEffect,useMemo,useState} from 'react';
import type {KaraokeLine} from '../lib/karaoke';
import {analyzeLyricsConfidence} from '../lib/lyrics-confidence';
import LyricsTranslationTrack from './LyricsTranslationTrack';

type Props={audioUrl:string;duration:number;timeline:KaraokeLine[];onSeek?:(time:number,lineIndex:number)=>void};
const badge={high:'bg-emerald-300/10 text-emerald-200',medium:'bg-amber-300/10 text-amber-100',low:'bg-red-300/10 text-red-200'};
const label={high:'Tốt',medium:'Cần xem',low:'Thấp'};

export default function LyricsConfidencePanel({audioUrl,duration,timeline,onSeek}:Props){
  const [peaks,setPeaks]=useState<number[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let cancelled=false,ctx:AudioContext|null=null;setLoading(true);setError('');(async()=>{try{const response=await fetch(audioUrl,{cache:'no-store'});if(!response.ok)throw new Error('Không tải được audio');const Ctx=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!Ctx)throw new Error('Trình duyệt không hỗ trợ AudioContext');ctx=new Ctx();const buffer=await ctx.decodeAudioData((await response.arrayBuffer()).slice(0));const channel=buffer.getChannelData(0),bins=Math.min(900,Math.max(240,Math.floor((window.innerWidth||360)*1.5))),step=Math.max(1,Math.floor(channel.length/bins)),next:number[]=[];for(let i=0;i<bins;i++){let max=0;const from=i*step,to=Math.min(channel.length,from+step);for(let j=from;j<to;j++)max=Math.max(max,Math.abs(channel[j]));next.push(max);if(i%100===0)await new Promise<void>(r=>setTimeout(r,0));}if(!cancelled)setPeaks(next)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Không phân tích được audio')}finally{if(!cancelled)setLoading(false);if(ctx)void ctx.close().catch(()=>{})}})();return()=>{cancelled=true;if(ctx)void ctx.close().catch(()=>{})}},[audioUrl]);
  const report=useMemo(()=>analyzeLyricsConfidence(timeline,peaks,duration),[timeline,peaks,duration]);
  const low=useMemo(()=>report.lines.flatMap(line=>line.words).filter(word=>word.level==='low').sort((a,b)=>a.score-b.score),[report]);
  const translation=<LyricsTranslationTrack timeline={timeline}/>;
  if(loading)return <><section className="mt-3 rounded-xl border border-white/10 bg-white/[.025] p-3 text-xs text-white/45">Đang phân tích confidence từ waveform…</section>{translation}</>;
  if(error)return <><section className="mt-3 rounded-xl border border-red-300/15 bg-red-300/[.04] p-3 text-xs text-red-100">Lyrics Confidence: {error}</section>{translation}</>;
  return <><section className="mt-3 rounded-xl border border-violet-300/15 bg-violet-300/[.04] p-3"><div className="flex items-center justify-between gap-3"><div><b className="text-xs">Auto Lyrics Confidence</b><p className="mt-1 text-[10px] text-white/40">Chấm timing theo onset, năng lượng waveform, độ dài từ và khoảng hở.</p></div><span className={`rounded-lg px-2.5 py-1.5 text-xs font-black ${badge[report.level]}`}>{report.score}% · {label[report.level]}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-[10px]"><div className="rounded-lg bg-white/5 p-2"><b className="block text-sm">{report.lines.length}</b><span className="text-white/35">dòng</span></div><div className="rounded-lg bg-white/5 p-2"><b className="block text-sm">{report.lines.reduce((n,l)=>n+l.words.length,0)}</b><span className="text-white/35">từ</span></div><div className="rounded-lg bg-white/5 p-2"><b className="block text-sm text-red-200">{report.lowCount}</b><span className="text-white/35">cần sửa</span></div></div>{low.length>0&&<div className="mt-3"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-red-200/80">Timing confidence thấp</p><div className="flex max-h-32 flex-wrap gap-1.5 overflow-y-auto">{low.slice(0,24).map(word=>{const item=timeline[word.lineIndex]?.words[word.wordIndex];return <button key={`${word.lineIndex}-${word.wordIndex}`} onClick={()=>item&&onSeek?.(item.start,word.lineIndex)} title={word.reasons.join(' · ')} className="rounded-lg border border-red-300/15 bg-red-300/[.06] px-2 py-1.5 text-[10px] text-red-100">{item?.text||'?'} · {word.score}%</button>})}</div></div>}</section>{translation}</>;
}
