import V4SafePage from '@/components/v4/page-safe';
import {V5DownloadEnhancer} from '@/components/v5/download-enhancer';
import {V5PresetGalleryEnhancer} from '@/components/v5/preset-gallery-enhancer';
import {V6BackgroundRenderEnhancer} from '@/components/v6/background-render-enhancer';
import {V7AppShell} from '@/components/v7/app-shell';
import {V8EffectsPanel} from '@/components/v8/effects-panel';
import {V8DefaultSunoSample} from '@/components/v8/default-suno-sample';
import {V8DesignLayoutEnhancer} from '@/components/v8/design-layout-enhancer';
import {V10LibraryEnhancer} from '@/components/v10/local-library';
const faq=[{question:'Cách tải nhạc Suno về điện thoại?',answer:'Sao chép liên kết bài hát Suno, dán vào Suno Tools, chờ hệ thống nhận diện rồi chọn MP3, WAV, M4A, video, ảnh bìa hoặc lời bài hát để lưu.'},{question:'Có thể tải Suno MP3, WAV và M4A không?',answer:'Có. Công cụ hỗ trợ tải M4A và chuyển đổi sang MP3 hoặc WAV trực tiếp trên trình duyệt khi thiết bị hỗ trợ.'},{question:'Có thể tải video Suno không?',answer:'Có. Bạn có thể tải video gốc khi nguồn có video hoặc tạo video sóng nhạc từ bài hát.'},{question:'Có tải được ảnh bìa và lời bài hát Suno không?',answer:'Có. Khi dữ liệu có sẵn, bạn có thể lưu ảnh bìa, lời bài hát và thông tin bài hát.'},{question:'Có cần cài ứng dụng để tải nhạc Suno không?',answer:'Không. Suno Tools chạy trực tiếp trên trình duyệt điện thoại và máy tính.'}];
const structuredData={'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Suno Tools',url:'https://suno.aiautotool.com/',applicationCategory:'MultimediaApplication',operatingSystem:'Web',inLanguage:'vi',description:'Công cụ tải nhạc Suno MP3, WAV, M4A, video, ảnh bìa, lời bài hát và tạo video sóng nhạc.',offers:{'@type':'Offer',price:'0',priceCurrency:'VND'},featureList:['Tải Suno MP3','Tải Suno WAV','Tải Suno M4A','Tải video Suno','Tải ảnh bìa Suno','Tải lyrics Suno','Tạo video sóng nhạc']},{'@type':'FAQPage',mainEntity:faq.map(x=>({'@type':'Question',name:x.question,acceptedAnswer:{'@type':'Answer',text:x.answer}}))}]};
export default function Page(){return <><V8DefaultSunoSample/><V8DesignLayoutEnhancer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><V7AppShell><style>{`.v7-workspace main{min-height:0!important;background:transparent!important}.v7-workspace main>section{padding:0!important;max-width:none!important}.v7-workspace main>section>p:first-child,.v7-workspace main>section>h1{display:none!important}.v7-workspace article{background:linear-gradient(180deg,#0a1727,#081421)!important;border:1px solid rgba(139,92,246,.16)!important;border-radius:18px!important}.v7-workspace input{background:#09192b!important}@media(max-width:767px){.v7-workspace{padding-left:12px!important;padding-right:12px!important}.v7-workspace article{padding:14px!important}}`}</style><div className="mx-auto max-w-5xl"><section className="mb-4 rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/[.12] to-cyan-500/[.05] p-4 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">Tải nhạc Suno trực tuyến</p><h1 className="mt-2 text-xl font-bold sm:text-3xl">Tải nhạc Suno miễn phí — MP3, WAV, M4A & Video</h1><p className="mt-2 max-w-3xl text-xs leading-5 text-white/45 sm:text-sm">Dán liên kết Suno để tải âm thanh, video, ảnh bìa và lời bài hát hoặc tạo video sóng nhạc.</p></section><V4SafePage/><div id="download"><V5DownloadEnhancer/></div><div id="presets"><V5PresetGalleryEnhancer/></div><V8EffectsPanel/><V6BackgroundRenderEnhancer/><div id="library"><V10LibraryEnhancer/></div></div></V7AppShell><section id="help" className="border-t border-white/[.06] bg-[#06101d] px-4 pb-24 pt-9 text-white md:pb-10"><div className="mx-auto max-w-5xl"><h2 className="text-xl font-bold">Câu hỏi thường gặp về tải nhạc Suno</h2><div className="mt-4 space-y-2">{faq.map(x=><details key={x.question} className="rounded-xl border border-white/[.07] bg-[#0a1727] p-4"><summary className="cursor-pointer text-xs font-semibold">{x.question}</summary><p className="mt-2 text-xs leading-5 text-white/40">{x.answer}</p></details>)}</div><p className="mt-8 text-[10px] text-white/25">Chỉ tải và sử dụng nội dung mà bạn có quyền lưu hoặc sử dụng.</p></div></section></>}
