'use client';

import {useEffect, useRef, useState} from 'react';
import {Bell, BookOpen, ChevronDown, FileText, Folder, Image as ImageIcon, Link2, ListMusic, Menu, Music2, Pause, Play, Plus, Settings, SlidersHorizontal, Sparkles, Upload, Volume2} from 'lucide-react';
import {generateVisualizerVideoArt} from '@/components/v7/renderer-art';
import {VIDEO_EFFECTS,type EffectConfig,type VideoEffect} from '@/components/v8/video-effects';
import {LivePreview} from '@/components/v8/live-preview';
import {WAVE_STYLES,VISUAL_TEMPLATES,type WaveStyle,type VisualTemplate,type VideoAspect,type LyricsMode} from '@/components/v4/types';

type Song={title:string;creator?:string;duration?:number;picture?:string;audio:string;video?:string;lyrics?:string;style?:string;tags?:string};

const fmt=(n=0)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const valid=(value:string)=>{try{const u=new URL(value);return u.protocol==='https:'&&(u.hostname==='suno.com'||u.hostname.endsWith('.suno.com'))}catch{return false}};
const renderSong=(song:Song)=>({id:null,title:song.title,picture:song.picture||null,audio:song.audio,sourceAudio:song.audio,video:song.video||null,description:null,lyrics:song.lyrics||null,style:song.style||null,tags:song.tags||null,duration:song.duration||null,creator:song.creator||null});

function ToolControls(p:{panel:string;setPanel:(v:string)=>void;wave:WaveStyle;setWave:(v:WaveStyle)=>void;template:VisualTemplate;setTemplate:(v:VisualTemplate)=>void;aspect:VideoAspect;setAspect:(v:VideoAspect)=>void;lyrics:LyricsMode;setLyrics:(v:LyricsMode)=>void;effects:VideoEffect[];setEffects:(v:VideoEffect[])=>void}){
 const rows=[['style','Style',Sparkles],['wave','Waveform',SlidersHorizontal],['lyrics','Lyrics',FileText],['format','Format',SlidersHorizontal],['effects','Effects',Sparkles]] as const;
 const toggle=(id:VideoEffect)=>p.setEffects(p.effects.includes(id)?p.effects.filter(x=>x!==id):[...p.effects,id]);
 return <>{rows.map(([id,label,Icon])=><div className="sd-fold" key={id}><button onClick={()=>p.setPanel(p.panel===id?'':id)}><Icon/><b>{label}</b><ChevronDown/></button>{p.panel===id&&<div className="sd-options">{id==='style'&&VISUAL_TEMPLATES.map(x=><button className={p.template===x.id?'active':''} onClick={()=>p.setTemplate(x.id)} key={x.id}>{x.label}</button>)}{id==='wave'&&WAVE_STYLES.map(x=><button className={p.wave===x.id?'active':''} onClick={()=>p.setWave(x.id)} key={x.id}>{x.label}</button>)}{id==='lyrics'&&(['off','scroll','focus'] as LyricsMode[]).map(x=><button className={p.lyrics===x?'active':''} onClick={()=>p.setLyrics(x)} key={x}>{x==='off'?'Off':x==='scroll'?'Scroll':'Karaoke'}</button>)}{id==='format'&&(['16:9','9:16','1:1','4:5'] as VideoAspect[]).map(x=><button className={p.aspect===x?'active':''} onClick={()=>p.setAspect(x)} key={x}>{x}</button>)}{id==='effects'&&VIDEO_EFFECTS.map(x=><button className={p.effects.includes(x.id)?'active':''} onClick={()=>toggle(x.id)} key={x.id}>{x.icon} {x.label}</button>)}</div>}</div>)}</>;
}

export default function CreatorStudio(){
 const[url,setUrl]=useState(''),[song,setSong]=useState<Song|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[panel,setPanel]=useState('style'),[mobileTools,setMobileTools]=useState(false);
 const[wave,setWave]=useState<WaveStyle>('bars'),[template,setTemplate]=useState<VisualTemplate>('cover-motion'),[aspect,setAspect]=useState<VideoAspect>('16:9'),[lyrics,setLyrics]=useState<LyricsMode>('focus'),[effects,setEffects]=useState<VideoEffect[]>([]),[rendering,setRendering]=useState(false),[progress,setProgress]=useState(0);
 const audio=useRef<HTMLAudioElement>(null),timer=useRef<number|undefined>(undefined);
 async function resolve(value=url){if(!valid(value)){setError('Paste a valid Suno link.');return}setBusy(true);setError('');try{const r=await fetch('/api/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:value})}),data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load this song.');setSong(data);setTime(0)}catch(e){setError(e instanceof Error?e.message:'Unable to load this song.')}finally{setBusy(false)}}
 function change(value:string){setUrl(value);setError('');if(timer.current)clearTimeout(timer.current);if(valid(value.trim()))timer.current=window.setTimeout(()=>void resolve(value.trim()),350)}
 async function paste(){const value=await navigator.clipboard.readText();change(value)}
 async function toggle(){if(!audio.current)return;if(audio.current.paused){await audio.current.play();setPlaying(true)}else{audio.current.pause();setPlaying(false)}}
 function seek(value:number){if(audio.current)audio.current.currentTime=value;setTime(value)}
 async function renderVideo(){if(!song||rendering)return;setRendering(true);setProgress(0);setError('');try{const config:EffectConfig={effects,intensity:1,speed:1,opacity:.75,wind:0};const blob=await generateVisualizerVideoArt(renderSong(song),aspect,wave,template,{motion:'medium',lyrics,onProgress:setProgress,effects:config});const object=URL.createObjectURL(blob),a=document.createElement('a');a.href=object;a.download=`${(song.title||'suno').replace(/[\\/:*?"<>|]/g,'-')}.mp4`;a.click();setTimeout(()=>URL.revokeObjectURL(object),2000)}catch(e){setError(e instanceof Error?e.message:'Không thể tạo video.')}finally{setRendering(false)}}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{const config:EffectConfig={effects,intensity:1,speed:1,opacity:.75,wind:0};localStorage.setItem('suno-v8-video-effects',JSON.stringify(config));window.dispatchEvent(new CustomEvent('suno-effects-change',{detail:config}))},[effects]);
 return <div className="sd-app">
  <header className="sd-header"><div className="sd-brand"><span><Music2/></span><b>SunoDown</b></div>{song?<div className="sd-loaded"><i>✓</i> Suno song loaded</div>:<div/>}<div className="sd-head-actions"><Bell/><span className="sd-avatar">S</span><ChevronDown/></div></header>
  <aside className="sd-sidebar"><nav>{[[Plus,'Create'],[Folder,'Projects'],[BookOpen,'Library'],[ListMusic,'Jobs'],[Settings,'Settings']].map(([Icon,label],i)=><button key={String(label)} className={i===0?'active':''}>{<Icon/>}<span>{String(label)}</span></button>)}</nav></aside>
  {!song?<main className="sd-empty"><div className="sd-mobile-brand"><div className="sd-brand"><span><Music2/></span><b>SunoDown</b></div><Menu/></div><div className="sd-empty-content"><p>CREATOR STUDIO</p><h1>Turn your Suno song<br/><em>into content</em></h1><div className="sd-input"><Link2/><input value={url} onChange={e=>change(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void resolve()} placeholder="Paste a Suno link"/><button onClick={paste}>Paste</button></div><button className="sd-analyze" disabled={busy} onClick={()=>resolve()}>{busy?'Analyzing…':'Analyze'}</button>{error&&<div className="sd-error">{error}</div>}<span className="sd-choose">Choose what to create</span><div className="sd-intents"><button className="active"><Play/><span>Social Video</span></button><button><Music2/><span>Audio</span></button><button><FileText/><span>Lyrics</span></button></div></div><div className="sd-landscape"/><small>MUSIC LIVES FURTHER</small></main>:
  <main className="sd-studio">
   <section className="sd-canvas-column"><div className="sd-mobile-title"><button onClick={()=>setSong(null)}>‹</button><img src={song.picture}/><div><b>{song.title}</b><span>{fmt(song.duration)} · Suno song</span></div><Menu/></div><div className="sd-stage sd-live-preview"><LivePreview song={renderSong(song)} aspect={aspect} template={template} wave={wave} motion="medium" lyrics={lyrics} start={0} exporting={rendering}/></div><div className="sd-player"><button onClick={toggle}>{playing?<Pause/>:<Play/>}</button><span>{fmt(time)} / {fmt(song.duration)}</span><input type="range" min="0" max={song.duration||1} value={time} onChange={e=>seek(+e.target.value)}/><Volume2/><SlidersHorizontal/></div><audio ref={audio} src={song.audio} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)}/><div className="sd-timeline"><div className="sd-ruler"><span>00:00</span><span>00:30</span><span>01:00</span><span>01:30</span><span>02:00</span><span>02:30</span><span>03:00</span></div><div className="sd-film">{[0,1,2,3,4,5].map(i=><div key={i} style={{backgroundImage:`url(${song.picture})`}}/>)}<i/></div></div></section>
   <aside className="sd-inspector"><div className="sd-song"><img src={song.picture}/><div><h2>{song.title}</h2><p>Created by {song.creator||'Suno'}</p><span>{fmt(song.duration)}</span></div></div><hr/><h3>Recommended</h3><div className="sd-presets">{VISUAL_TEMPLATES.slice(0,4).map((x,i)=><button onClick={()=>setTemplate(x.id)} className={template===x.id?'active':''} key={x.id}><span style={{backgroundImage:`url(${song.picture})`}}/><small>{x.label}</small></button>)}</div><ToolControls panel={panel} setPanel={setPanel} wave={wave} setWave={setWave} template={template} setTemplate={setTemplate} aspect={aspect} setAspect={setAspect} lyrics={lyrics} setLyrics={setLyrics} effects={effects} setEffects={setEffects}/><button className="sd-export" disabled={rendering} onClick={renderVideo}><Upload/> {rendering?`Rendering ${Math.round(progress)}%`:'Create & export video'}</button>{rendering&&<div className="sd-progress"><i style={{width:`${progress}%`}}/></div>}<div className="sd-downloads"><a href={song.audio} download><Music2/>Audio</a>{song.picture&&<a href={song.picture} download><ImageIcon/>Cover</a>}</div></aside>
   <div className="sd-mobile-export"><button disabled={rendering} onClick={renderVideo}><Upload/>{rendering?`Rendering ${Math.round(progress)}%`:'Create & export video'}</button><nav><button onClick={()=>{setPanel('style');setMobileTools(true)}}><Sparkles/>Style</button><button onClick={()=>{setPanel('lyrics');setMobileTools(true)}}><FileText/>Lyrics</button><button onClick={()=>{setPanel('wave');setMobileTools(true)}}><Music2/>Wave</button><button onClick={renderVideo}><Upload/>Export</button></nav></div>
  </main>}
  {song&&mobileTools&&<div className="sd-tool-sheet"><div className="sd-sheet-head"><b>Video controls</b><button onClick={()=>setMobileTools(false)}>×</button></div><ToolControls panel={panel} setPanel={setPanel} wave={wave} setWave={setWave} template={template} setTemplate={setTemplate} aspect={aspect} setAspect={setAspect} lyrics={lyrics} setLyrics={setLyrics} effects={effects} setEffects={setEffects}/></div>}
 </div>
}
