'use client';

import {useEffect, useRef, useState} from 'react';
import {Bell, BookOpen, ChevronDown, FileText, Folder, Image as ImageIcon, Link2, ListMusic, Menu, Music2, Pause, Play, Plus, Settings, SlidersHorizontal, Sparkles, Upload, Volume2} from 'lucide-react';

type Song={title:string;creator?:string;duration?:number;picture?:string;audio:string;video?:string;lyrics?:string;style?:string;tags?:string};

const fmt=(n=0)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const valid=(value:string)=>{try{const u=new URL(value);return u.protocol==='https:'&&(u.hostname==='suno.com'||u.hostname.endsWith('.suno.com'))}catch{return false}};

export default function CreatorStudio(){
 const[url,setUrl]=useState(''),[song,setSong]=useState<Song|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[panel,setPanel]=useState('');
 const audio=useRef<HTMLAudioElement>(null),timer=useRef<number|undefined>(undefined);
 async function resolve(value=url){if(!valid(value)){setError('Paste a valid Suno link.');return}setBusy(true);setError('');try{const r=await fetch('/api/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:value})}),data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load this song.');setSong(data);setTime(0)}catch(e){setError(e instanceof Error?e.message:'Unable to load this song.')}finally{setBusy(false)}}
 function change(value:string){setUrl(value);setError('');if(timer.current)clearTimeout(timer.current);if(valid(value.trim()))timer.current=window.setTimeout(()=>void resolve(value.trim()),350)}
 async function paste(){const value=await navigator.clipboard.readText();change(value)}
 async function toggle(){if(!audio.current)return;if(audio.current.paused){await audio.current.play();setPlaying(true)}else{audio.current.pause();setPlaying(false)}}
 function seek(value:number){if(audio.current)audio.current.currentTime=value;setTime(value)}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 const background=song?.picture?{backgroundImage:`linear-gradient(180deg,rgba(4,7,12,.02),rgba(4,7,12,.34)),url(${song.picture})`}:undefined;
 return <div className="sd-app">
  <header className="sd-header"><div className="sd-brand"><span><Music2/></span><b>SunoDown</b></div>{song?<div className="sd-loaded"><i>✓</i> Suno song loaded</div>:<div/>}<div className="sd-head-actions"><Bell/><span className="sd-avatar">S</span><ChevronDown/></div></header>
  <aside className="sd-sidebar"><nav>{[[Plus,'Create'],[Folder,'Projects'],[BookOpen,'Library'],[ListMusic,'Jobs'],[Settings,'Settings']].map(([Icon,label],i)=><button key={String(label)} className={i===0?'active':''}>{<Icon/>}<span>{String(label)}</span></button>)}</nav></aside>
  {!song?<main className="sd-empty"><div className="sd-mobile-brand"><div className="sd-brand"><span><Music2/></span><b>SunoDown</b></div><Menu/></div><div className="sd-empty-content"><p>CREATOR STUDIO</p><h1>Turn your Suno song<br/><em>into content</em></h1><div className="sd-input"><Link2/><input value={url} onChange={e=>change(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void resolve()} placeholder="Paste a Suno link"/><button onClick={paste}>Paste</button></div><button className="sd-analyze" disabled={busy} onClick={()=>resolve()}>{busy?'Analyzing…':'Analyze'}</button>{error&&<div className="sd-error">{error}</div>}<span className="sd-choose">Choose what to create</span><div className="sd-intents"><button className="active"><Play/><span>Social Video</span></button><button><Music2/><span>Audio</span></button><button><FileText/><span>Lyrics</span></button></div></div><div className="sd-landscape"/><small>MUSIC LIVES FURTHER</small></main>:
  <main className="sd-studio">
   <section className="sd-canvas-column"><div className="sd-mobile-title"><button onClick={()=>setSong(null)}>‹</button><img src={song.picture}/><div><b>{song.title}</b><span>{fmt(song.duration)} · Suno song</span></div><Menu/></div><div className="sd-stage" style={background}><div className="sd-karaoke"><strong>{song.lyrics?.split('\n').filter(Boolean)[0]||song.title}</strong><span>{song.lyrics?.split('\n').filter(Boolean)[1]||song.creator}</span></div></div><div className="sd-player"><button onClick={toggle}>{playing?<Pause/>:<Play/>}</button><span>{fmt(time)} / {fmt(song.duration)}</span><input type="range" min="0" max={song.duration||1} value={time} onChange={e=>seek(+e.target.value)}/><Volume2/><SlidersHorizontal/></div><audio ref={audio} src={song.audio} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)}/><div className="sd-timeline"><div className="sd-ruler"><span>00:00</span><span>00:30</span><span>01:00</span><span>01:30</span><span>02:00</span><span>02:30</span><span>03:00</span></div><div className="sd-film">{[0,1,2,3,4,5].map(i=><div key={i} style={{backgroundImage:`url(${song.picture})`}}/>)}<i/></div></div></section>
   <aside className="sd-inspector"><div className="sd-song"><img src={song.picture}/><div><h2>{song.title}</h2><p>Created by {song.creator||'Suno'}</p><span>{fmt(song.duration)}</span></div></div><hr/><h3>Recommended</h3><div className="sd-presets">{['Cinematic','Portrait','Minimal','Vintage'].map((x,i)=><button className={i===0?'active':''} key={x}><span style={{backgroundImage:`url(${song.picture})`}}/><small>{x}</small></button>)}</div>{[['lyrics','Lyrics',FileText],['format','Format',SlidersHorizontal],['audio','Audio',Music2]].map(([id,label,Icon])=><div className="sd-fold" key={String(id)}><button onClick={()=>setPanel(panel===id?'':String(id))}>{<Icon/>}<b>{String(label)}</b><ChevronDown/></button>{panel===id&&<div>{id==='lyrics'?(song.lyrics||'No lyrics available'):id==='format'?'9:16 · 1080 × 1920':'Original audio · High quality'}</div>}</div>)}<a className="sd-export" href={song.video||song.audio} download><Upload/> Export video</a><div className="sd-downloads"><a href={song.audio} download><Music2/>Audio</a>{song.picture&&<a href={song.picture} download><ImageIcon/>Cover</a>}</div></aside>
   <div className="sd-mobile-export"><a href={song.video||song.audio} download><Upload/>Export video</a><nav><button><Sparkles/>Style</button><button><FileText/>Lyrics</button><button><Music2/>Audio</button><button><Upload/>Export</button></nav></div>
  </main>}
 </div>
}
