'use client';
import {useEffect,useState} from 'react';
const INSTALLATION_KEY='suno-installation-id';
function installationId(){let id=localStorage.getItem(INSTALLATION_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(INSTALLATION_KEY,id)}return id}
function b64(s:string){const p='='.repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export function V6BackgroundRenderEnhancer(){
 const[permission,setPermission]=useState<NotificationPermission|'unsupported'>(()=>typeof Notification==='undefined'?'unsupported':Notification.permission),[job,setJob]=useState<any>(null);
 useEffect(()=>{navigator.serviceWorker?.register('/sw.js').catch(()=>{});const q=new URLSearchParams(location.search).get('renderJob');if(q)fetch(`/api/render/jobs/${encodeURIComponent(q)}`).then(r=>r.ok?r.json():null).then(d=>d&&setJob(d)).catch(()=>{})},[]);
 useEffect(()=>{if(!job||['completed','failed'].includes(job.status))return;const t=setInterval(async()=>{try{const r=await fetch(`/api/render/jobs/${job.id}`,{cache:'no-store'});if(r.ok)setJob(await r.json())}catch{}},3000);return()=>clearInterval(t)},[job?.id,job?.status]);
 async function enableNotify(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){setPermission('unsupported');return}const p=await Notification.requestPermission();setPermission(p);if(p!=='granted')return;const keyRes=await fetch('/api/push/key'),{publicKey}=await keyRes.json();if(!keyRes.ok||!publicKey)throw new Error('Push chưa được cấu hình trên máy chủ.');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(publicKey)});const r=await fetch('/api/push/subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:installationId(),subscription:sub.toJSON()})});if(!r.ok)throw new Error('Không lưu được đăng ký thông báo.')}
 async function startBackground(){const root=document.querySelector('article');if(!root)return;const title=root.querySelector('h2')?.textContent?.trim()||'Suno video';const selected=(needle:string)=>Array.from(root.querySelectorAll('button')).find(b=>b.className.includes(needle))?.textContent?.trim();const payload={installationId:installationId(),title,preset:selected('border-emerald-300/50')||'custom',template:selected('border-fuchsia-300/50')||'Ảnh bìa chuyển động',aspect:selected('border-violet-300/50')||'9:16',wave:selected('border-cyan-300/50')||'Bars',motion:selected('border-amber-300/50')||'Vừa',lyrics:selected('border-pink-300/50')||'Tắt',backgroundKey:document.documentElement.dataset.sunoBackground||'suno',backgroundMode:document.documentElement.dataset.sunoBackgroundMode||'suno'};const r=await fetch('/api/render/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Không tạo được tác vụ xuất video nền');setJob(d)}
 useEffect(()=>{const button=Array.from(document.querySelectorAll('button')).find(b=>b.textContent?.includes('Xuất toàn bộ video')) as HTMLButtonElement|undefined;if(!button||document.getElementById('v6-background-render'))return;const box=document.createElement('div');box.id='v6-background-render';box.className='mt-3 rounded-2xl border border-violet-300/20 bg-violet-300/[.06] p-4';button.closest('.grid')?.parentElement?.appendChild(box);const mount=()=>{box.innerHTML=`<div><p class="text-sm font-bold text-violet-100">Xuất video nền <span class="ml-1 rounded-md bg-violet-300/10 px-1.5 py-0.5 text-[9px]">v6</span></p><p class="mt-1 text-xs leading-5 text-white/45">Đóng web vẫn tiếp tục. Xuất video xong có thể báo trên điện thoại.</p></div><div class="mt-3 grid gap-2 sm:grid-cols-2"><button data-bg-render class="h-11 rounded-xl bg-violet-500 font-bold text-white">☁️ Xuất video nền</button><button data-notify class="h-11 rounded-xl border border-white/10 bg-white/[.05] text-sm font-bold">${permission==='granted'?'🔔 Đã cho phép thông báo':'🔔 Bật thông báo khi xong'}</button></div>${job?`<div class="mt-3 rounded-xl bg-black/20 p-3"><div class="flex justify-between text-xs"><span>${job.status}</span><b>${job.progress||0}%</b></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><i class="block h-full rounded-full bg-violet-400" style="width:${job.progress||0}%"></i></div>${job.resultUrl?`<a class="mt-3 block text-xs font-bold text-cyan-300" href="${job.resultUrl}">▶ Xem video đã xuất</a>`:''}${job.error?`<p class="mt-2 text-xs text-red-300">${job.error}</p>`:''}<p class="mt-2 break-all text-[10px] text-white/35">Tác vụ: ${job.id}</p></div>`:''}`;box.querySelector('[data-bg-render]')?.addEventListener('click',()=>startBackground().catch(e=>alert(e.message)));box.querySelector('[data-notify]')?.addEventListener('click',()=>enableNotify().catch(e=>alert(e.message)))};mount()},[permission,job]);return null}
