'use client';

import { useEffect, useState } from 'react';

const INSTALLATION_KEY='suno-installation-id';
function installationId(){let id=localStorage.getItem(INSTALLATION_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(INSTALLATION_KEY,id)}return id}

export function V6BackgroundRenderEnhancer(){
 const[permission,setPermission]=useState<NotificationPermission|'unsupported'>(()=>typeof Notification==='undefined'?'unsupported':Notification.permission);
 const[job,setJob]=useState<{id:string;status:string;progress:number}|null>(null);
 useEffect(()=>{navigator.serviceWorker?.register('/sw.js').catch(()=>{});const q=new URLSearchParams(location.search).get('renderJob');if(q)fetch(`/api/render/jobs/${encodeURIComponent(q)}`).then(r=>r.ok?r.json():null).then(d=>d&&setJob(d)).catch(()=>{})},[]);
 useEffect(()=>{if(!job||['completed','failed'].includes(job.status))return;const t=setInterval(async()=>{try{const r=await fetch(`/api/render/jobs/${job.id}`,{cache:'no-store'});if(r.ok)setJob(await r.json())}catch{}},3000);return()=>clearInterval(t)},[job?.id,job?.status]);
 async function enableNotify(){if(!('Notification'in window)||!('serviceWorker'in navigator)){setPermission('unsupported');return}const p=await Notification.requestPermission();setPermission(p);if(p==='granted'){const reg=await navigator.serviceWorker.ready;await fetch('/api/push/subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:installationId(),capability:'notification',scope:reg.scope})}).catch(()=>{})}}
 async function startBackground(){const root=document.querySelector('article');if(!root)return;const title=root.querySelector('h2')?.textContent?.trim()||'Suno video';const selected=(needle:string)=>Array.from(root.querySelectorAll('button')).find(b=>b.className.includes(needle))?.textContent?.trim();const payload={installationId:installationId(),title,preset:selected('border-emerald-300/50')||'custom',template:selected('border-fuchsia-300/50')||'Cover Motion',aspect:selected('border-violet-300/50')||'9:16',wave:selected('border-cyan-300/50')||'Bars',motion:selected('border-amber-300/50')||'Vừa',lyrics:selected('border-pink-300/50')||'Tắt'};const r=await fetch('/api/render/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Không tạo được job render ngầm');setJob(d)}
 useEffect(()=>{const labels=Array.from(document.querySelectorAll('button')).filter(b=>b.textContent?.includes('Render full'));const button=labels[0] as HTMLButtonElement|undefined;if(!button||document.getElementById('v6-background-render'))return;const box=document.createElement('div');box.id='v6-background-render';box.className='mt-3 rounded-2xl border border-violet-300/20 bg-violet-300/[.06] p-4';button.closest('.grid')?.parentElement?.appendChild(box);const mount=()=>{box.innerHTML=`<div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold text-violet-100">Render ngầm <span class="ml-1 rounded-md bg-violet-300/10 px-1.5 py-0.5 text-[9px]">v6</span></p><p class="mt-1 text-xs leading-5 text-white/45">Đóng web vẫn tiếp tục. Khi backend render hoàn tất, điện thoại có thể nhận thông báo.</p></div></div><div class="mt-3 grid gap-2 sm:grid-cols-2"><button data-bg-render class="h-11 rounded-xl bg-violet-500 font-bold text-white">☁️ Render ngầm</button><button data-notify class="h-11 rounded-xl border border-white/10 bg-white/[.05] text-sm font-bold">${permission==='granted'?'🔔 Đã bật thông báo':'🔔 Bật thông báo khi xong'}</button></div>${job?`<div class="mt-3 rounded-xl bg-black/20 p-3"><div class="flex justify-between text-xs"><span>${job.status}</span><b>${job.progress||0}%</b></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><i class="block h-full rounded-full bg-violet-400" style="width:${job.progress||0}%"></i></div><p class="mt-2 break-all text-[10px] text-white/35">Job: ${job.id}</p></div>`:''}`;box.querySelector('[data-bg-render]')?.addEventListener('click',()=>startBackground().catch(e=>alert(e.message)));box.querySelector('[data-notify]')?.addEventListener('click',enableNotify)};mount()},[permission,job]);
 return null;
}
