'use client';

import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react';
import { ChevronDown, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { StudioSize, StudioTone } from './tokens';

export function StudioButton({tone='default',size='md',className,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{tone?:StudioTone;size?:StudioSize}){return <button data-studio="button" data-tone={tone} data-size={size} className={cn('studio-button',className)} {...props}/>;}
export function StudioIconButton({label,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <StudioButton className="studio-icon-button" aria-label={label} title={label} {...props}/>;}
export function StudioPanel({className,...props}:HTMLAttributes<HTMLDivElement>){return <div data-studio="panel" className={cn('studio-panel',className)} {...props}/>;}
export function StudioCard({selected=false,className,...props}:HTMLAttributes<HTMLDivElement>&{selected?:boolean}){return <div data-studio="card" data-selected={selected} className={cn('studio-card',className)} {...props}/>;}
export function StudioBadge({tone='default',className,...props}:HTMLAttributes<HTMLSpanElement>&{tone?:StudioTone}){return <span data-studio="badge" data-tone={tone} className={cn('studio-badge',className)} {...props}/>;}
export function StudioDivider({className,...props}:HTMLAttributes<HTMLHRElement>){return <hr data-studio="divider" className={cn('studio-divider',className)} {...props}/>;}
export function StudioStack({direction='vertical',gap='md',className,...props}:HTMLAttributes<HTMLDivElement>&{direction?:'vertical'|'horizontal';gap?:StudioSize}){return <div data-studio="stack" data-direction={direction} data-gap={gap} className={cn('studio-stack',className)} {...props}/>;}
export function StudioToggle({checked,onChange,label,description}:{checked:boolean;onChange:(v:boolean)=>void;label:string;description?:string}){return <StudioButton className="studio-toggle-row" aria-pressed={checked} onClick={()=>onChange(!checked)}><span><b>{label}</b>{description&&<small>{description}</small>}</span><i data-checked={checked}/></StudioButton>;}
export function StudioControlRow({label,value,hint,children}:{label:string;value?:ReactNode;hint?:string;children:ReactNode}){return <div className="studio-control-row"><div><b>{label}</b>{value&&<span>{value}</span>}</div>{children}{hint&&<small>{hint}</small>}</div>;}
export function StudioField({label,hint,error,children}:{label:string;hint?:string;error?:string;children:ReactNode}){return <label className="studio-field"><b>{label}</b>{children}{error?<small data-error>{error}</small>:hint&&<small>{hint}</small>}</label>;}
export function StudioInput({className,...props}:InputHTMLAttributes<HTMLInputElement>){return <input data-studio="input" className={cn('studio-input',className)} {...props}/>;}
export function StudioTextarea({className,...props}:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea data-studio="textarea" className={cn('studio-input studio-textarea',className)} {...props}/>;}
export function StudioSelect({className,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <select data-studio="select" className={cn('studio-input studio-select',className)} {...props}/>;}
export function StudioSlider({value,min=0,max=100,step=1,onChange,label}:{value:number;min?:number;max?:number;step?:number;onChange:(v:number)=>void;label?:string}){return <input aria-label={label} data-studio="slider" className="studio-slider" type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(+e.target.value)}/>;}
export function StudioSegmented<T extends string>({value,options,onChange}:{value:T;options:{value:T;label:string}[];onChange:(v:T)=>void}){return <div data-studio="segmented" className="studio-segmented">{options.map(o=><button key={o.value} className={value===o.value?'active':''} onClick={()=>onChange(o.value)}>{o.label}</button>)}</div>;}
export function StudioTabs<T extends string>({value,tabs,onChange}:{value:T;tabs:{value:T;label:string;icon?:ReactNode}[];onChange:(v:T)=>void}){return <nav data-studio="tabs" className="studio-tabs">{tabs.map(t=><button key={t.value} className={value===t.value?'active':''} onClick={()=>onChange(t.value)}>{t.icon}<span>{t.label}</span></button>)}</nav>;}
export function StudioAccordion({icon,title,open,onToggle,children}:{icon?:ReactNode;title:string;open:boolean;onToggle:()=>void;children?:ReactNode}){return <section data-studio="accordion" className="studio-accordion"><button className="studio-accordion-trigger" aria-expanded={open} onClick={onToggle}>{icon}<b>{title}</b><ChevronDown/></button>{open&&<div className="studio-accordion-content">{children}</div>}</section>;}
export function StudioSheet({title,onClose,children,className}:{title:string;onClose:()=>void;children:ReactNode;className?:string}){return <div data-studio="sheet" className={cn('studio-sheet',className)}><header><b>{title}</b><StudioIconButton size="sm" label="Đóng" onClick={onClose}><X/></StudioIconButton></header><div className="studio-sheet-body">{children}</div></div>;}
export function StudioProgress({value,label}:{value:number;label?:string}){const n=Math.max(0,Math.min(100,value));return <div className="studio-progress-wrap">{label&&<div><span>{label}</span><b>{Math.round(n)}%</b></div>}<div className="studio-progress"><i style={{width:n+'%'}}/></div></div>;}
export function StudioEmpty({icon,title,description,action}:{icon?:ReactNode;title:string;description?:string;action?:ReactNode}){return <div className="studio-empty">{icon}<b>{title}</b>{description&&<p>{description}</p>}{action}</div>;}
export function StudioStatus({tone='default',children}:{tone?:StudioTone;children:ReactNode}){return <span className="studio-status" data-tone={tone}><i/>{children}</span>;}
export function StudioToolbar({children,className}:HTMLAttributes<HTMLDivElement>){return <div data-studio="toolbar" className={cn('studio-toolbar',className)}>{children}</div>;}
export function StudioModal({open,title,description,onClose,children,footer}:{open:boolean;title:string;description?:string;onClose:()=>void;children:ReactNode;footer?:ReactNode}){if(!open)return null;return <div className="studio-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="studio-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><b>{title}</b>{description&&<small>{description}</small>}</div><StudioIconButton label="Đóng" onClick={onClose}><X/></StudioIconButton></header><div className="studio-modal-body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>;}
export function StudioSkeleton({className,...props}:HTMLAttributes<HTMLDivElement>){return <div className={cn('studio-skeleton',className)} aria-hidden="true" {...props}/>;}
export function StudioToast({tone='default',children}: {tone?:StudioTone;children:ReactNode}){return <div className="studio-toast" data-tone={tone} role="status">{children}</div>;}
