'use client';
import {useEffect,useMemo,useState} from 'react';
export type FilenameKind='audio'|'video'|'subtitle'|'package';
export type FilenameContext={title?:string;creator?:string;index?:number;template?:string;aspect?:string;ext?:string;date?:Date;count?:number};
export const DEFAULT_FILENAME_TEMPLATES:Record<FilenameKind,string>={audio:'{index}-{title}',video:'{title}-{template}-{aspect}',subtitle:'{index}-{title}',package:'sunodown-{count}-songs'};
const KEY='sunodown-v9-filename-templates';
export function sanitizeFilename(value:string){return (value||'suno').normalize('NFC').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'-').replace(/\s+/g,' ').replace(/[. ]+$/,'').trim().slice(0,160)||'suno'}
export function renderFilenameTemplate(template:string,ctx:FilenameContext){const d=ctx.date||new Date(),tokens:Record<string,string>={title:ctx.title||'suno',creator:ctx.creator||'',index:String(ctx.index??1).padStart(2,'0'),template:ctx.template||'',aspect:ctx.aspect||'',ext:ctx.ext||'',count:String(ctx.count??1),date:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};return sanitizeFilename(template.replace(/\{([a-z]+)\}/gi,(_,k)=>tokens[k.toLowerCase()]??'').replace(/-+/g,'-'))}
export function loadFilenameTemplates(){if(typeof window==='undefined')return DEFAULT_FILENAME_TEMPLATES;try{return {...DEFAULT_FILENAME_TEMPLATES,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return DEFAULT_FILENAME_TEMPLATES}}
export function FilenameTemplatePanel(){const [value,setValue]=useState(DEFAULT_FILENAME_TEMPLATES);useEffect(()=>setValue(loadFilenameTemplates()),[]);const save=(kind:FilenameKind,v:string)=>{const next={...value,[kind]:v};setValue(next);localStorage.setItem(KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('suno-v9-filename-templates',{detail:next}))};const preview=useMemo(()=>({audio:renderFilenameTemplate(value.audio,{index:1,title:'My Suno Song',creator:'Artist'}),video:renderFilenameTemplate(value.video,{title:'My Suno Song',template:'cover-motion',aspect:'9x16'}),subtitle:renderFilenameTemplate(value.subtitle,{index:1,title:'My Suno Song'}),package:renderFilenameTemplate(value.package,{count:5})}),[value]);return <details className="rounded-2xl border border-white/[.06] bg-white/[.02] p-4"><summary className="cursor-pointer text-sm font-bold">Tên file xuất</summary><p className="mt-2 text-[10px] text-white/40">Token: {'{title} {creator} {index} {template} {aspect} {count} {date}'}</p><div className="mt-3 grid gap-3">{(['audio','video','subtitle','package'] as FilenameKind[]).map(kind=><label key={kind} className="grid gap-1"><span className="text-[11px] font-semibold capitalize">{kind}</span><input value={value[kind]} onChange={e=>save(kind,e.target.value)} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-xs"/><span className="truncate text-[10px] text-cyan-200/60">→ {preview[kind]}</span></label>)}</div></details>}
