'use client';
export type SubtitleFont='system'|'serif'|'rounded'|'mono'|'impact';
export type SubtitleStyle={preset:'classic'|'karaoke'|'caption'|'minimal'|'neon'|'boxed';color:string;activeColor:string;background:string;backgroundOpacity:number;fontSize:number;font:SubtitleFont;bold:boolean;shadow:boolean;outline:boolean;radius:number};
export const DEFAULT_SUBTITLE_STYLE:SubtitleStyle={preset:'karaoke',color:'#ffffff',activeColor:'#f0abfc',background:'#080812',backgroundOpacity:68,fontSize:100,font:'system',bold:true,shadow:true,outline:true,radius:28};
const PRESETS:Record<SubtitleStyle['preset'],Partial<SubtitleStyle>>={
 classic:{color:'#ffffff',activeColor:'#ffffff',background:'#000000',backgroundOpacity:0,font:'serif',bold:true,shadow:true,outline:true,radius:0},
 karaoke:{color:'#ffffff',activeColor:'#f0abfc',background:'#080812',backgroundOpacity:68,font:'system',bold:true,shadow:true,outline:true,radius:28},
 caption:{color:'#ffffff',activeColor:'#ffffff',background:'#000000',backgroundOpacity:78,font:'rounded',bold:true,shadow:false,outline:false,radius:10},
 minimal:{color:'#ffffff',activeColor:'#ffffff',background:'#000000',backgroundOpacity:0,font:'system',bold:false,shadow:true,outline:false,radius:0},
 neon:{color:'#ffffff',activeColor:'#22d3ee',background:'#07131c',backgroundOpacity:42,font:'rounded',bold:true,shadow:true,outline:false,radius:30},
 boxed:{color:'#111827',activeColor:'#111827',background:'#ffffff',backgroundOpacity:92,font:'impact',bold:true,shadow:false,outline:false,radius:8}
};
const FONTS:Record<SubtitleFont,{label:string;css:string}>={system:{label:'Modern',css:'system-ui,-apple-system,sans-serif'},serif:{label:'Serif',css:'Georgia,serif'},rounded:{label:'Rounded',css:'"Trebuchet MS",Arial,sans-serif'},mono:{label:'Mono',css:'"Courier New",monospace'},impact:{label:'Impact',css:'Impact,"Arial Black",sans-serif'}};
function hexToRgba(hex:string,opacity:number){const value=hex.replace('#','');const n=parseInt(value,16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${Math.max(0,Math.min(100,opacity))/100})`}
export function SubtitleStylePanel({value,onChange,onClose}:{value:SubtitleStyle;onChange:(v:SubtitleStyle)=>void;onClose?:()=>void}){
 const safe={...DEFAULT_SUBTITLE_STYLE,...value};const set=(p:Partial<SubtitleStyle>)=>onChange({...safe,...p});
 return <div className="fixed inset-0 z-50 bg-black/55 backdrop-blur-sm" onPointerDown={e=>{if(e.target===e.currentTarget)onClose?.()}}><aside className="absolute inset-x-0 bottom-0 max-h-[88vh] overflow-y-auto rounded-t-3xl border border-white/10 bg-[#101017] p-5 shadow-2xl sm:inset-y-0 sm:left-auto sm:right-0 sm:w-[440px] sm:max-h-none sm:rounded-none sm:rounded-l-3xl"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-fuchsia-300">Subtitle Styling Studio</p><b className="text-sm">Preset, font, màu, nền và hiệu ứng</b><p className="mt-1 text-[10px] text-white/35">Thay đổi áp dụng ngay lên preview và video render.</p></div><button type="button" onClick={onClose} className="rounded-xl bg-white/5 px-3 py-2 text-xs">Đóng</button></div>
 <div className="rounded-2xl border border-white/10 bg-gradient-to-b from-[#15223a] to-[#070911] p-5"><div className="flex min-h-24 items-end justify-center"><div className="max-w-full px-4 py-3 text-center" style={{fontFamily:FONTS[safe.font].css,fontSize:`${Math.max(15,22*safe.fontSize/100)}px`,fontWeight:safe.bold?800:500,color:safe.color,background:hexToRgba(safe.background,safe.backgroundOpacity),borderRadius:safe.radius,textShadow:safe.shadow?'0 3px 12px rgba(0,0,0,.9)':'none',WebkitTextStroke:safe.outline?'1px rgba(0,0,0,.8)':'0'}}><span>Em vẫn </span><span style={{color:safe.activeColor}}>chờ anh</span><span> nơi đây</span></div></div><p className="mt-3 text-center text-[9px] uppercase tracking-widest text-white/25">Live style preview</p></div>
 <div className="mt-4 grid grid-cols-3 gap-2">{(Object.keys(PRESETS) as SubtitleStyle['preset'][]).map(p=><button key={p} type="button" onClick={()=>set({preset:p,...PRESETS[p]})} className={`rounded-xl border px-2 py-2.5 text-xs capitalize ${safe.preset===p?'border-fuchsia-300 bg-fuchsia-300/10':'border-white/5 bg-white/[.03]'}`}>{p}</button>)}</div>
 <div className="mt-4"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-white/40">Font</p><div className="flex gap-2 overflow-x-auto pb-1">{(Object.keys(FONTS) as SubtitleFont[]).map(font=><button key={font} type="button" onClick={()=>set({font})} style={{fontFamily:FONTS[font].css}} className={`shrink-0 rounded-xl border px-3 py-2 text-xs ${safe.font===font?'border-cyan-300/50 bg-cyan-300/10 text-cyan-100':'border-white/5 bg-white/[.03]'}`}>{FONTS[font].label}</button>)}</div></div>
 <div className="mt-4 grid grid-cols-2 gap-3 text-xs"><label className="rounded-xl bg-black/20 p-3">Màu chữ<input type="color" value={safe.color} onChange={e=>set({color:e.target.value})} className="mt-2 h-9 w-full"/></label><label className="rounded-xl bg-black/20 p-3">Màu karaoke<input type="color" value={safe.activeColor} onChange={e=>set({activeColor:e.target.value})} className="mt-2 h-9 w-full"/></label><label className="rounded-xl bg-black/20 p-3">Màu nền<input type="color" value={safe.background} onChange={e=>set({background:e.target.value})} className="mt-2 h-9 w-full"/></label><label className="rounded-xl bg-black/20 p-3">Độ mờ nền <b>{safe.backgroundOpacity}%</b><input type="range" min="0" max="100" value={safe.backgroundOpacity} onChange={e=>set({backgroundOpacity:+e.target.value})} className="mt-3 w-full accent-fuchsia-300"/></label></div>
 <label className="mt-4 block text-xs">Cỡ chữ <b>{safe.fontSize}%</b><input type="range" min="60" max="180" value={safe.fontSize} onChange={e=>set({fontSize:+e.target.value})} className="mt-2 w-full accent-fuchsia-300"/></label>
 <label className="mt-4 block text-xs">Bo góc nền <b>{safe.radius}px</b><input type="range" min="0" max="48" value={safe.radius} onChange={e=>set({radius:+e.target.value})} className="mt-2 w-full accent-fuchsia-300"/></label>
 <div className="mt-4 flex flex-wrap gap-2">{([['bold','Đậm'],['shadow','Bóng'],['outline','Viền']] as const).map(([k,label])=><button key={k} type="button" onClick={()=>set({[k]:!safe[k]})} className={`min-h-10 rounded-lg px-4 py-2 text-xs ${safe[k]?'bg-fuchsia-300/15 text-fuchsia-100 ring-1 ring-fuchsia-300/20':'bg-white/5 text-white/45'}`}>{label}</button>)}<button type="button" onClick={()=>onChange(DEFAULT_SUBTITLE_STYLE)} className="ml-auto min-h-10 rounded-lg bg-white/5 px-4 py-2 text-xs text-white/55">Đặt lại</button></div></aside></div>
}
