type ZipSink={write:(data:Uint8Array)=>Promise<void>;close:()=>Promise<void>};
type Central={name:Uint8Array;crc:number;size:number;offset:number};
const enc=new TextEncoder();
let crcTable:Uint32Array|undefined;
function table(){if(crcTable)return crcTable;crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}return crcTable}
function crcUpdate(crc:number,data:Uint8Array){const t=table();let c=crc^0xffffffff;for(const b of data)c=t[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function u16(v:number){return [v&255,(v>>>8)&255]}
function u32(v:number){return [v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]}
function bytes(...values:number[][]){return new Uint8Array(values.flat())}
function safe(value:string){return (value||'suno').normalize('NFC').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'-').replace(/\s+/g,' ').trim().slice(0,120)||'suno'}
function srtTime(seconds:number){const ms=Math.max(0,Math.round(seconds*1000)),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000),x=ms%1000;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(x).padStart(3,'0')}`}
export function lyricsToSrt(lyrics:string,duration:number){const lines=(lyrics||'').split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!/^\[.*\]$/.test(x));if(!lines.length)return '';const step=Math.max(.8,(duration||lines.length*4)/lines.length);return lines.map((line,i)=>`${i+1}\n${srtTime(i*step)} --> ${srtTime(Math.min(duration||Infinity,(i+1)*step))}\n${line}\n`).join('\n')}
async function sinkFor(name:string):Promise<{sink:ZipSink;download?:()=>void}>{const picker=(window as unknown as {showSaveFilePicker?:Function}).showSaveFilePicker;if(picker){const handle=await picker({suggestedName:name,types:[{description:'ZIP package',accept:{'application/zip':['.zip']}}]});const writable=await handle.createWritable();return {sink:{write:async d=>{await writable.write(d)},close:async()=>{await writable.close()}}}}const parts:BlobPart[]=[];return {sink:{write:async d=>{parts.push(d.slice().buffer as ArrayBuffer)},close:async()=>{}},download:()=>{const blob=new Blob(parts,{type:'application/zip'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}}}
export async function createZipPackage(opts:{name:string;items:{url:string}[];video?:Blob|null;videoName?:string;onProgress?:(done:number,total:number,label:string)=>void}){const out=await sinkFor(`${safe(opts.name)}.zip`),central:Central[]=[];let offset=0;const write=async(d:Uint8Array)=>{await out.sink.write(d);offset+=d.byteLength};
 const addStream=async(name:string,stream:ReadableStream<Uint8Array>)=>{const n=enc.encode(name),start=offset,flags=0x0808;await write(bytes(u32(0x04034b50),u16(20),u16(flags),u16(0),u16(0),u16(0),u32(0),u32(0),u32(0),u16(n.length),u16(0)));await write(n);let crc=0,size=0;const reader=stream.getReader();while(true){const {done,value}=await reader.read();if(done)break;if(value){crc=crcUpdate(crc,value);size+=value.byteLength;await write(value)}}await write(bytes(u32(0x08074b50),u32(crc),u32(size),u32(size)));central.push({name:n,crc,size,offset:start})};
 const addBlob=(name:string,blob:Blob)=>addStream(name,blob.stream());const total=opts.items.length+(opts.video?1:0);let done=0;
 for(let i=0;i<opts.items.length;i++){const item=opts.items[i],rr=await fetch('/api/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:item.url})}),song=await rr.json();if(!rr.ok||!song?.audio)throw new Error(song?.error||`Không đọc được bài ${i+1}`);const base=`${String(i+1).padStart(2,'0')}-${safe(song.title)}`,ar=await fetch(song.audio,{cache:'no-store'});if(!ar.ok||!ar.body)throw new Error(`Không tải được audio: ${song.title}`);const type=(ar.headers.get('content-type')||'').toLowerCase(),ext=type.includes('mp4')||type.includes('m4a')?'m4a':'mp3';await addStream(`${base}.${ext}`,ar.body);if(song.lyrics){const srt=lyricsToSrt(song.lyrics,Number(song.duration)||0);if(srt)await addBlob(`${base}.srt`,new Blob([srt],{type:'text/plain;charset=utf-8'}))}done++;opts.onProgress?.(done,total,song.title||base)}
 if(opts.video){await addBlob(opts.videoName||'rendered-video.mp4',opts.video);done++;opts.onProgress?.(done,total,'Video')}
 const centralStart=offset;for(const c of central){await write(bytes(u32(0x02014b50),u16(20),u16(20),u16(0x0808),u16(0),u16(0),u16(0),u32(c.crc),u32(c.size),u32(c.size),u16(c.name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(c.offset)));await write(c.name)}const centralSize=offset-centralStart;await write(bytes(u32(0x06054b50),u16(0),u16(0),u16(central.length),u16(central.length),u32(centralSize),u32(centralStart),u16(0)));await out.sink.close();out.download?.();return central.length}
