'use client';

import type { Song, VideoAspect, VisualTemplate, WaveStyle } from './types';
import { VIDEO_SIZES } from './types';

function coverFit(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,w:number,h:number,scaleExtra=1,dx=0,dy=0){const s=Math.min(w/bmp.width,h/bmp.height)*scaleExtra,iw=bmp.width*s,ih=bmp.height*s;ctx.drawImage(bmp,(w-iw)/2+dx,(h-ih)/2+dy,iw,ih)}
function coverFill(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,w:number,h:number,alpha=.32,blur=28,scaleExtra=1,dx=0,dy=0){const s=Math.max(w/bmp.width,h/bmp.height)*scaleExtra,iw=bmp.width*s,ih=bmp.height*s;ctx.save();ctx.globalAlpha=alpha;ctx.filter=`blur(${blur}px)`;ctx.drawImage(bmp,(w-iw)/2+dx,(h-ih)/2+dy,iw,ih);ctx.restore()}
function wrap(ctx:CanvasRenderingContext2D,text:string,maxW:number,maxLines=2){const words=text.trim().split(/\s+/).filter(Boolean),lines:string[]=[];let line='';for(const word of words){const n=line?`${line} ${word}`:word;if(!line||ctx.measureText(n).width<=maxW)line=n;else{lines.push(line);line=word;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);return lines}
function drawMeta(ctx:CanvasRenderingContext2D,song:Song,w:number,y:number,align:'center'|'left'='center',max=.76){ctx.save();const fs=Math.max(24,Math.min(48,Math.round(w*.036)));ctx.font=`700 ${fs}px system-ui,-apple-system,sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle='rgba(255,255,255,.98)';ctx.shadowColor='rgba(0,0,0,.65)';ctx.shadowBlur=16;const lines=wrap(ctx,song.title||'Suno Track',w*max,2),lh=fs*1.16,x=align==='center'?w/2:w*.1;lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lh));if(song.creator){ctx.shadowBlur=8;ctx.font=`500 ${Math.max(16,Math.round(fs*.47))}px system-ui,-apple-system,sans-serif`;ctx.fillStyle='rgba(255,255,255,.72)';ctx.fillText(song.creator,x,y+lines.length*lh+Math.max(10,fs*.18))}ctx.restore()}
function amplitude(samples:Float32Array|null,rate:number,t:number,off:number){if(!samples)return Math.max(.08,.2+.15*Math.sin((t+off)*5));const c=Math.max(0,Math.min(samples.length-1,Math.floor((t+off)*rate))),r=Math.max(64,Math.floor(rate*.012)),from=Math.max(0,c-r),to=Math.min(samples.length,c+r),stride=Math.max(1,Math.floor((to-from)/24));let sum=0,n=0;for(let i=from;i<to;i+=stride){sum+=Math.abs(samples[i]);n++}return n?Math.min(1,(sum/n)*5.2):.08}

function drawWave(ctx:CanvasRenderingContext2D,samples:Float32Array|null,rate:number,t:number,w:number,h:number,style:WaveStyle){const ph=Math.max(110,Math.round(h*.14)),top=h-ph,bg=ctx.createLinearGradient(0,top,0,h);bg.addColorStop(0,'rgba(6,7,18,0)');bg.addColorStop(.3,'rgba(6,7,18,.55)');bg.addColorStop(1,'rgba(6,7,18,.95)');ctx.fillStyle=bg;ctx.fillRect(0,top,w,ph);const n=Math.max(42,Math.min(92,Math.round(w/14))),usable=w*.84,start=w*.08,cy=h-ph*.42,max=ph*.52,vals=Array.from({length:n},(_,i)=>Math.max(.05,amplitude(samples,rate,t,((i/(n-1))-.5)*.7)));const grad=ctx.createLinearGradient(start,0,start+usable,0);grad.addColorStop(0,'#67e8f9');grad.addColorStop(.5,'#a78bfa');grad.addColorStop(1,'#e879f9');ctx.save();ctx.fillStyle=grad;ctx.strokeStyle=grad;ctx.shadowColor='rgba(167,139,250,.5)';ctx.shadowBlur=12;ctx.lineCap='round';ctx.lineJoin='round';if(style==='line'){ctx.lineWidth=Math.max(3,w*.003);ctx.beginPath();vals.forEach((a,i)=>{const x=start+i/(n-1)*usable,y=cy-(a-.15)*max*(.9+.1*Math.sin(t*7+i*.2));i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}else if(style==='dots'){vals.forEach((a,i)=>{const x=start+i/(n-1)*usable,y=cy-(a-.15)*max,r=Math.max(2.5,w*.003)*(1+a);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()})}else{const gap=Math.max(3,w*.004),bw=Math.max(3,(usable-gap*(n-1))/n);vals.forEach((a,i)=>{const x=start+i*(bw+gap),pulse=.82+.18*Math.sin(t*7+i*.3),hh=Math.max(6,max*a*pulse*(style==='pulse'?1.25:1));if(style==='mirror'){ctx.beginPath();ctx.roundRect(x,cy-hh,bw,hh*2,bw/2);ctx.fill()}else{ctx.globalAlpha=style==='pulse'?.65+.35*pulse:1;ctx.beginPath();ctx.roundRect(x,cy-hh/2,bw,hh,bw/2);ctx.fill()}})}ctx.restore()}

function drawCoverMotion(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number){ctx.fillStyle='#070711';ctx.fillRect(0,0,w,h);const zoom=1.06+.025*Math.sin(t*.45)+level*.02,dx=Math.sin(t*.22)*w*.018,dy=Math.cos(t*.18)*h*.014;coverFill(ctx,bmp,w,h,.5,34,zoom,dx,dy);ctx.fillStyle='rgba(3,4,12,.25)';ctx.fillRect(0,0,w,h);ctx.save();ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=30;coverFit(ctx,bmp,w*.82,h*.72,1+.018*Math.sin(t*.5),dx*.25,dy*.25);ctx.restore();drawMeta(ctx,song,w,h*.67,'center',.72)}
function drawVinyl(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number){ctx.fillStyle='#080812';ctx.fillRect(0,0,w,h);coverFill(ctx,bmp,w,h,.34,42,1.08);const portrait=h>w,cx=portrait?w/2:w*.36,cy=portrait?h*.39:h*.46,r=Math.min(w,h)*(portrait?.28:.29);ctx.save();ctx.translate(cx,cy);ctx.rotate(t*.32);ctx.fillStyle='#111116';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();for(let i=0;i<12;i++){ctx.strokeStyle=`rgba(255,255,255,${.035+i*.003})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,r*(.42+i*.045),0,Math.PI*2);ctx.stroke()}ctx.save();ctx.beginPath();ctx.arc(0,0,r*.58,0,Math.PI*2);ctx.clip();const s=Math.max((r*1.16)/bmp.width,(r*1.16)/bmp.height),iw=bmp.width*s,ih=bmp.height*s;ctx.drawImage(bmp,-iw/2,-ih/2,iw,ih);ctx.restore();ctx.fillStyle='#0b0b10';ctx.beginPath();ctx.arc(0,0,r*.08,0,Math.PI*2);ctx.fill();ctx.restore();if(portrait)drawMeta(ctx,song,w,h*.72,'center',.8);else drawMeta(ctx,song,w,h*.26,'left',.48)}
function drawGlass(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number){ctx.fillStyle='#090913';ctx.fillRect(0,0,w,h);coverFill(ctx,bmp,w,h,.52,46,1.12+level*.03,Math.sin(t*.2)*w*.025,Math.cos(t*.17)*h*.018);const orbs:[[number,number,string],[number,number,string],[number,number,string]]=[[.18,.24,'rgba(34,211,238,.24)'],[.82,.2,'rgba(168,85,247,.26)'],[.72,.72,'rgba(236,72,153,.19)']];orbs.forEach(([ox,oy,c],i)=>{ctx.save();ctx.filter='blur(28px)';ctx.fillStyle=c;ctx.beginPath();ctx.arc(w*(ox+.02*Math.sin(t*.22+i)),h*(oy+.02*Math.cos(t*.18+i)),Math.min(w,h)*(.11+i*.015),0,Math.PI*2);ctx.fill();ctx.restore()});const portrait=h>w,cw=w*(portrait?.78:.72),ch=h*(portrait?.54:.62),x=(w-cw)/2,y=h*(portrait?.17:.13);ctx.beginPath();ctx.roundRect(x,y,cw,ch,Math.max(22,w*.025));ctx.fillStyle='rgba(12,12,28,.52)';ctx.fill();ctx.strokeStyle='rgba(255,255,255,.15)';ctx.stroke();ctx.save();ctx.beginPath();ctx.roundRect(x+cw*.08,y+ch*.08,cw*.84,ch*(portrait?.56:.7),Math.max(16,w*.018));ctx.clip();const aw=cw*.84,ah=ch*(portrait?.56:.7),s=Math.min(aw/bmp.width,ah/bmp.height),iw=bmp.width*s,ih=bmp.height*s;ctx.drawImage(bmp,x+cw*.08+(aw-iw)/2,y+ch*.08+(ah-ih)/2,iw,ih);ctx.restore();drawMeta(ctx,song,w,y+ch*(portrait?.72:.83),'center',.62)}
function drawTemplate(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number,template:VisualTemplate){if(template==='vinyl')drawVinyl(ctx,bmp,song,w,h,t);else if(template==='glass-card')drawGlass(ctx,bmp,song,w,h,t,level);else drawCoverMotion(ctx,bmp,song,w,h,t,level)}

export async function generateVisualizerVideo(song:Song,aspect:VideoAspect,waveStyle:WaveStyle,template:VisualTemplate){if(!song.picture||!song.audio)throw new Error('Không đủ ảnh hoặc audio để tự tạo video.');const[ir,ar]=await Promise.all([fetch(song.picture,{cache:'no-store'}),fetch(song.audio,{cache:'no-store'})]);if(!ir.ok||!ar.ok)throw new Error('Không thể tải ảnh hoặc audio để tạo video.');if(!('VideoEncoder'in window))throw new Error('Trình duyệt chưa hỗ trợ tạo video MP4.');const{ALL_FORMATS,BlobSource,BufferTarget,CanvasSource,EncodedAudioPacketSource,EncodedPacketSink,Input,Mp4OutputFormat,Output}=await import('mediabunny');const audioBlob=await ar.blob(),input=new Input({source:new BlobSource(audioBlob),formats:ALL_FORMATS}),track=await input.getPrimaryAudioTrack();if(!track)throw new Error('Không có track audio hợp lệ.');const codec=await track.getCodec(),decoderConfig=await track.getDecoderConfig(),duration=await input.computeDuration();if(!codec||!decoderConfig||!Number.isFinite(duration)||duration<=0)throw new Error('Không đọc được audio.');let samples:Float32Array|null=null,rate=48000;try{const ac=new AudioContext(),d=await ac.decodeAudioData(await audioBlob.arrayBuffer());samples=d.getChannelData(0);rate=d.sampleRate;await ac.close()}catch{}const{width,height}=VIDEO_SIZES[aspect],canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Không tạo được canvas.');const bmp=await createImageBitmap(await ir.blob()),target=new BufferTarget(),output=new Output({format:new Mp4OutputFormat(),target}),bitrate=width*height>=1_000_000?2_500_000:1_800_000,videoSource=new CanvasSource(canvas,{codec:'avc',bitrate}),audioSource=new EncodedAudioPacketSource(codec);output.addVideoTrack(videoSource);output.addAudioTrack(audioSource,{decoderConfig});await output.start();try{const fps=15,fd=1/fps,frames=Math.ceil(duration*fps);for(let i=0;i<frames;i++){const t=i*fd,level=amplitude(samples,rate,t,0);drawTemplate(ctx,bmp,song,width,height,t,level,template);drawWave(ctx,samples,rate,t,width,height,waveStyle);await videoSource.add(t,Math.min(fd,duration-t),{keyFrame:i%(fps*2)===0})}bmp.close();const sink=new EncodedPacketSink(track),meta={decoderConfig};for await(const p of sink.packets())await audioSource.add(p,meta);await output.finalize()}catch(e){bmp.close();output.cancel();throw e}if(!target.buffer)throw new Error('Không xuất được MP4.');return new Blob([target.buffer],{type:'video/mp4'})}
