'use client';

import type { LyricsMode, MotionIntensity, Song, VideoAspect, VisualTemplate, WaveStyle } from './types';
import { VIDEO_SIZES } from './types';

const MOTION_GAIN: Record<MotionIntensity,number> = { low:.45, medium:1, high:1.75 };

function clamp(v:number,min=0,max=255){return Math.max(min,Math.min(max,v))}
function rgb(c:[number,number,number],a=1){return `rgba(${c[0]},${c[1]},${c[2]},${a})`}
function coverFit(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,w:number,h:number,scaleExtra=1,dx=0,dy=0){const s=Math.min(w/bmp.width,h/bmp.height)*scaleExtra,iw=bmp.width*s,ih=bmp.height*s;ctx.drawImage(bmp,(w-iw)/2+dx,(h-ih)/2+dy,iw,ih)}
function coverFill(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,w:number,h:number,alpha=.34,blur=30,scaleExtra=1,dx=0,dy=0){const s=Math.max(w/bmp.width,h/bmp.height)*scaleExtra,iw=bmp.width*s,ih=bmp.height*s;ctx.save();ctx.globalAlpha=alpha;ctx.filter=`blur(${blur}px)`;ctx.drawImage(bmp,(w-iw)/2+dx,(h-ih)/2+dy,iw,ih);ctx.restore()}
function wrap(ctx:CanvasRenderingContext2D,text:string,maxW:number,maxLines=2){const words=text.trim().split(/\s+/).filter(Boolean),lines:string[]=[];let line='';for(const word of words){const n=line?`${line} ${word}`:word;if(!line||ctx.measureText(n).width<=maxW)line=n;else{lines.push(line);line=word;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);return lines}
function amplitude(samples:Float32Array|null,rate:number,t:number,off=0){if(!samples)return Math.max(.08,.2+.15*Math.sin((t+off)*5));const c=Math.max(0,Math.min(samples.length-1,Math.floor((t+off)*rate))),r=Math.max(64,Math.floor(rate*.012)),from=Math.max(0,c-r),to=Math.min(samples.length,c+r),stride=Math.max(1,Math.floor((to-from)/24));let sum=0,n=0;for(let i=from;i<to;i+=stride){sum+=Math.abs(samples[i]);n++}return n?Math.min(1,(sum/n)*5.2):.08}

function extractPalette(bmp:ImageBitmap):[[number,number,number],[number,number,number],[number,number,number]]{const c=document.createElement('canvas');c.width=32;c.height=32;const x=c.getContext('2d',{willReadFrequently:true});if(!x)return [[103,232,249],[167,139,250],[232,121,249]];x.drawImage(bmp,0,0,32,32);const d=x.getImageData(0,0,32,32).data;let r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=16){const lum=(d[i]+d[i+1]+d[i+2])/3;if(lum<25||lum>235)continue;r+=d[i];g+=d[i+1];b+=d[i+2];n++}if(!n)return [[103,232,249],[167,139,250],[232,121,249]];const base:[number,number,number]=[r/n,g/n,b/n].map(v=>Math.round(v)) as [number,number,number];const a:[number,number,number]=[clamp(base[0]+55),clamp(base[1]+40),clamp(base[2]+65)] as [number,number,number];const z:[number,number,number]=[clamp(base[2]+35),clamp(base[0]+20),clamp(base[1]+45)] as [number,number,number];return [base,a,z]}

function drawMeta(ctx:CanvasRenderingContext2D,song:Song,w:number,y:number,align:'center'|'left'='center',max=.76){ctx.save();const fs=Math.max(24,Math.min(48,Math.round(w*.036)));ctx.font=`700 ${fs}px system-ui,-apple-system,sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle='rgba(255,255,255,.98)';ctx.shadowColor='rgba(0,0,0,.65)';ctx.shadowBlur=16;const lines=wrap(ctx,song.title||'Suno Track',w*max,2),lh=fs*1.16,x=align==='center'?w/2:w*.1;lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lh));if(song.creator){ctx.shadowBlur=8;ctx.font=`500 ${Math.max(16,Math.round(fs*.47))}px system-ui,-apple-system,sans-serif`;ctx.fillStyle='rgba(255,255,255,.72)';ctx.fillText(song.creator,x,y+lines.length*lh+Math.max(10,fs*.18))}ctx.restore()}

function lyricLines(song:Song){return (song.lyrics||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function drawLyrics(ctx:CanvasRenderingContext2D,song:Song,w:number,h:number,t:number,duration:number,mode:LyricsMode){if(mode==='off'||!song.lyrics)return;const lines=lyricLines(song);if(!lines.length)return;const idx=Math.min(lines.length-1,Math.floor((t/Math.max(1,duration))*lines.length));ctx.save();const fs=Math.max(22,Math.min(44,Math.round(w*.031)));ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`700 ${fs}px system-ui,-apple-system,sans-serif`;ctx.shadowColor='rgba(0,0,0,.7)';ctx.shadowBlur=16;if(mode==='focus'){const current=lines[idx];const y=h*.58;const boxW=w*.82;ctx.fillStyle='rgba(5,5,16,.48)';ctx.beginPath();ctx.roundRect(w*.09,y-fs*1.4,boxW,fs*2.8,18);ctx.fill();ctx.fillStyle='rgba(255,255,255,.96)';wrap(ctx,current,boxW*.9,2).forEach((l,i,a)=>ctx.fillText(l,w/2,y+(i-(a.length-1)/2)*fs*1.16))}else{const prev=lines[Math.max(0,idx-1)],current=lines[idx],next=lines[Math.min(lines.length-1,idx+1)],ys=[h*.48,h*.57,h*.66];[prev,current,next].forEach((l,i)=>{ctx.globalAlpha=i===1?1:.35;ctx.fillStyle='white';ctx.fillText(l,w/2,ys[i],w*.78)})}ctx.restore()}

function waveGradient(ctx:CanvasRenderingContext2D,w:number,palette:[[number,number,number],[number,number,number],[number,number,number]]){const g=ctx.createLinearGradient(w*.08,0,w*.92,0);g.addColorStop(0,rgb(palette[0]));g.addColorStop(.5,rgb(palette[1]));g.addColorStop(1,rgb(palette[2]));return g}
function drawWave(ctx:CanvasRenderingContext2D,samples:Float32Array|null,rate:number,t:number,w:number,h:number,style:WaveStyle,palette:[[number,number,number],[number,number,number],[number,number,number]]){const ph=Math.max(110,Math.round(h*.14)),top=h-ph,bg=ctx.createLinearGradient(0,top,0,h);bg.addColorStop(0,'rgba(6,7,18,0)');bg.addColorStop(.3,'rgba(6,7,18,.55)');bg.addColorStop(1,'rgba(6,7,18,.95)');ctx.fillStyle=bg;ctx.fillRect(0,top,w,ph);const n=Math.max(42,Math.min(92,Math.round(w/14))),usable=w*.84,start=w*.08,cy=h-ph*.42,max=ph*.52,vals=Array.from({length:n},(_,i)=>Math.max(.05,amplitude(samples,rate,t,((i/(n-1))-.5)*.7)));const grad=waveGradient(ctx,w,palette);ctx.save();ctx.fillStyle=grad;ctx.strokeStyle=grad;ctx.shadowColor=rgb(palette[1],.55);ctx.shadowBlur=12;ctx.lineCap='round';ctx.lineJoin='round';if(style==='line'){ctx.lineWidth=Math.max(3,w*.003);ctx.beginPath();vals.forEach((a,i)=>{const x=start+i/(n-1)*usable,y=cy-(a-.15)*max*(.9+.1*Math.sin(t*7+i*.2));i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}else if(style==='dots'){vals.forEach((a,i)=>{const x=start+i/(n-1)*usable,y=cy-(a-.15)*max,r=Math.max(2.5,w*.003)*(1+a);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()})}else{const gap=Math.max(3,w*.004),bw=Math.max(3,(usable-gap*(n-1))/n);vals.forEach((a,i)=>{const x=start+i*(bw+gap),pulse=.82+.18*Math.sin(t*7+i*.3),hh=Math.max(6,max*a*pulse*(style==='pulse'?1.25:1));if(style==='mirror'){ctx.beginPath();ctx.roundRect(x,cy-hh,bw,hh*2,bw/2);ctx.fill()}else{ctx.globalAlpha=style==='pulse'?.65+.35*pulse:1;ctx.beginPath();ctx.roundRect(x,cy-hh/2,bw,hh,bw/2);ctx.fill()}})}ctx.restore()}

function drawCoverMotion(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number,gain:number){ctx.fillStyle='#070711';ctx.fillRect(0,0,w,h);const zoom=1.06+.025*Math.sin(t*.45)*gain+level*.025*gain,dx=Math.sin(t*.22)*w*.018*gain,dy=Math.cos(t*.18)*h*.014*gain;coverFill(ctx,bmp,w,h,.5,34,zoom,dx,dy);ctx.fillStyle='rgba(3,4,12,.25)';ctx.fillRect(0,0,w,h);ctx.save();ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=30+level*18;coverFit(ctx,bmp,w*.82,h*.72,1+.02*Math.sin(t*.5)*gain+level*.01*gain,dx*.25,dy*.25);ctx.restore();drawMeta(ctx,song,w,h*.67,'center',.72)}
function drawVinyl(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number,gain:number,palette:[[number,number,number],[number,number,number],[number,number,number]]){ctx.fillStyle='#080812';ctx.fillRect(0,0,w,h);coverFill(ctx,bmp,w,h,.34,42,1.08+level*.03*gain);const portrait=h>w,cx=portrait?w/2:w*.36,cy=portrait?h*.39:h*.46,r=Math.min(w,h)*(portrait?.28:.29)*(1+level*.015*gain);ctx.save();ctx.translate(cx,cy);ctx.rotate(t*(.24+.16*gain));ctx.shadowColor=rgb(palette[1],.35+.25*level);ctx.shadowBlur=22+level*26;ctx.fillStyle='#111116';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();for(let i=0;i<12;i++){ctx.strokeStyle=`rgba(255,255,255,${.035+i*.003})`;ctx.beginPath();ctx.arc(0,0,r*(.42+i*.045),0,Math.PI*2);ctx.stroke()}ctx.save();ctx.beginPath();ctx.arc(0,0,r*.58,0,Math.PI*2);ctx.clip();const s=Math.max((r*1.16)/bmp.width,(r*1.16)/bmp.height),iw=bmp.width*s,ih=bmp.height*s;ctx.drawImage(bmp,-iw/2,-ih/2,iw,ih);ctx.restore();ctx.fillStyle='#0b0b10';ctx.beginPath();ctx.arc(0,0,r*.08,0,Math.PI*2);ctx.fill();ctx.restore();if(portrait)drawMeta(ctx,song,w,h*.72,'center',.8);else drawMeta(ctx,song,w,h*.26,'left',.48)}
function drawGlass(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number,gain:number,palette:[[number,number,number],[number,number,number],[number,number,number]]){ctx.fillStyle='#090913';ctx.fillRect(0,0,w,h);coverFill(ctx,bmp,w,h,.52,46,1.12+level*.035*gain,Math.sin(t*.2)*w*.025*gain,Math.cos(t*.17)*h*.018*gain);palette.forEach((c,i)=>{ctx.save();ctx.filter='blur(32px)';ctx.fillStyle=rgb(c,.16+.2*level);ctx.beginPath();ctx.arc(w*(.18+i*.3+.025*Math.sin(t*.22+i)*gain),h*(.22+.22*(i%2)+.025*Math.cos(t*.18+i)*gain),Math.min(w,h)*(.1+i*.015),0,Math.PI*2);ctx.fill();ctx.restore()});const portrait=h>w,cw=w*(portrait?.78:.72),ch=h*(portrait?.54:.62),x=(w-cw)/2,y=h*(portrait?.17:.13);ctx.beginPath();ctx.roundRect(x,y,cw,ch,Math.max(22,w*.025));ctx.fillStyle='rgba(12,12,28,.52)';ctx.fill();ctx.strokeStyle=rgb(palette[1],.42);ctx.stroke();ctx.save();ctx.beginPath();ctx.roundRect(x+cw*.08,y+ch*.08,cw*.84,ch*(portrait?.56:.7),Math.max(16,w*.018));ctx.clip();const aw=cw*.84,ah=ch*(portrait?.56:.7),s=Math.min(aw/bmp.width,ah/bmp.height),iw=bmp.width*s,ih=bmp.height*s;ctx.drawImage(bmp,x+cw*.08+(aw-iw)/2,y+ch*.08+(ah-ih)/2,iw,ih);ctx.restore();drawMeta(ctx,song,w,y+ch*(portrait?.72:.83),'center',.62)}
function drawLyricsFocus(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number,gain:number,palette:[[number,number,number],[number,number,number],[number,number,number]]){ctx.fillStyle='#080812';ctx.fillRect(0,0,w,h);coverFill(ctx,bmp,w,h,.32,48,1.1+level*.03*gain);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,rgb(palette[0],.22));g.addColorStop(1,rgb(palette[2],.18));ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const r=Math.min(w,h)*(.11+level*.018*gain);ctx.save();ctx.beginPath();ctx.arc(w/2,h*.27,r,0,Math.PI*2);ctx.clip();coverFit(ctx,bmp,r*2,r*2,1);ctx.restore();drawMeta(ctx,song,w,h*.41,'center',.72)}

function drawTemplate(ctx:CanvasRenderingContext2D,bmp:ImageBitmap,song:Song,w:number,h:number,t:number,level:number,template:VisualTemplate,motion:MotionIntensity,palette:[[number,number,number],[number,number,number],[number,number,number]]){const gain=MOTION_GAIN[motion];if(template==='vinyl')drawVinyl(ctx,bmp,song,w,h,t,level,gain,palette);else if(template==='glass-card')drawGlass(ctx,bmp,song,w,h,t,level,gain,palette);else if(template==='lyrics-focus')drawLyricsFocus(ctx,bmp,song,w,h,t,level,gain,palette);else drawCoverMotion(ctx,bmp,song,w,h,t,level,gain)}

export type RenderOptions={motion:MotionIntensity;lyrics:LyricsMode;previewSeconds?:number};

export async function generateVisualizerVideo(song:Song,aspect:VideoAspect,waveStyle:WaveStyle,template:VisualTemplate,options:RenderOptions){if(!song.picture||!song.audio)throw new Error('Không đủ ảnh hoặc audio để tự tạo video.');const[ir,ar]=await Promise.all([fetch(song.picture,{cache:'no-store'}),fetch(song.audio,{cache:'no-store'})]);if(!ir.ok||!ar.ok)throw new Error('Không thể tải ảnh hoặc audio để tạo video.');if(!('VideoEncoder'in window))throw new Error('Trình duyệt chưa hỗ trợ tạo video MP4.');const{ALL_FORMATS,BlobSource,BufferTarget,CanvasSource,EncodedAudioPacketSource,EncodedPacketSink,Input,Mp4OutputFormat,Output}=await import('mediabunny');const audioBlob=await ar.blob(),input=new Input({source:new BlobSource(audioBlob),formats:ALL_FORMATS}),track=await input.getPrimaryAudioTrack();if(!track)throw new Error('Không có track audio hợp lệ.');const codec=await track.getCodec(),decoderConfig=await track.getDecoderConfig(),fullDuration=await input.computeDuration();if(!codec||!decoderConfig||!Number.isFinite(fullDuration)||fullDuration<=0)throw new Error('Không đọc được audio.');const duration=options.previewSeconds?Math.min(options.previewSeconds,fullDuration):fullDuration;let samples:Float32Array|null=null,rate=48000;try{const ac=new AudioContext(),d=await ac.decodeAudioData(await audioBlob.arrayBuffer());samples=d.getChannelData(0);rate=d.sampleRate;await ac.close()}catch{}const{width,height}=VIDEO_SIZES[aspect],canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Không tạo được canvas.');const bmp=await createImageBitmap(await ir.blob()),palette=extractPalette(bmp),target=new BufferTarget(),output=new Output({format:new Mp4OutputFormat(),target}),bitrate=width*height>=1_000_000?2_700_000:1_900_000,videoSource=new CanvasSource(canvas,{codec:'avc',bitrate}),audioSource=new EncodedAudioPacketSource(codec);output.addVideoTrack(videoSource);output.addAudioTrack(audioSource,{decoderConfig});await output.start();try{const fps=15,fd=1/fps,frames=Math.ceil(duration*fps);for(let i=0;i<frames;i++){const t=i*fd,level=amplitude(samples,rate,t);drawTemplate(ctx,bmp,song,width,height,t,level,template,options.motion,palette);drawLyrics(ctx,song,width,height,t,duration,options.lyrics);drawWave(ctx,samples,rate,t,width,height,waveStyle,palette);await videoSource.add(t,Math.min(fd,duration-t),{keyFrame:i%(fps*2)===0})}bmp.close();const sink=new EncodedPacketSink(track),meta={decoderConfig};for await(const p of sink.packets()){if(options.previewSeconds&&p.timestamp>=duration)break;await audioSource.add(p,meta)}await output.finalize()}catch(e){bmp.close();output.cancel();throw e}if(!target.buffer)throw new Error('Không xuất được MP4.');return new Blob([target.buffer],{type:'video/mp4'})}
